In [1]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt 
%matplotlib inline

In [2]:
df = pd.read_csv('diabetes.csv')

In [3]:
df.head()

,id,chol,stab.glu,hdl,ratio,glyhb,location,age,gender,height,weight,frame,bp.1s,bp.1d,bp.2s,bp.2d,waist,hip,time.ppn
0,1000,203.0,82,56.0,3.6,4.31,Buckingham,46,female,62.0,121.0,medium,118.0,59.0,NaN,NaN,29.0,38.0,720.0
1,1001,165.0,97,24.0,6.9,4.44,Buckingham,29,female,64.0,218.0,large,112.0,68.0,NaN,NaN,46.0,48.0,360.0
2,1002,228.0,92,37.0,6.2,4.64,Buckingham,58,female,61.0,256.0,large,190.0,92.0,185.0,92.0,49.0,57.0,180.0
3,1003,78.0,93,12.0,6.5,4.63,Buckingham,67,male,67.0,119.0,large,110.0,50.0,NaN,NaN,33.0,38.0,480.0
4,1005,249.0,90,28.0,8.9,7.72,Buckingham,64,male,68.0,183.0,medium,138.0,80.0,NaN,NaN,44.0,41.0,300.0

In [4]:
df['time.ppn']= df['time.ppn'].fillna(df['time.ppn'].median())

In [5]:
df['fasting']= (df['time.ppn'] >= 480).astype(int)

In [6]:
df = df.drop(['id','location','bp.2s','bp.2d','time.ppn'],axis = 1)

In [7]:
df.head()

,chol,stab.glu,hdl,ratio,glyhb,age,gender,height,weight,frame,bp.1s,bp.1d,waist,hip,fasting
0,203.0,82,56.0,3.6,4.31,46,female,62.0,121.0,medium,118.0,59.0,29.0,38.0,1
1,165.0,97,24.0,6.9,4.44,29,female,64.0,218.0,large,112.0,68.0,46.0,48.0,0
2,228.0,92,37.0,6.2,4.64,58,female,61.0,256.0,large,190.0,92.0,49.0,57.0,0
3,78.0,93,12.0,6.5,4.63,67,male,67.0,119.0,large,110.0,50.0,33.0,38.0,1
4,249.0,90,28.0,8.9,7.72,64,male,68.0,183.0,medium,138.0,80.0,44.0,41.0,0

In [8]:

df['height'] = df['height'].fillna(df['height'].median())
df['weight'] = df['weight'].fillna(df['weight'].median())
df['hdl'] = df['hdl'].fillna(df['hdl'].median())
df['waist'] = df['waist'].fillna(df['waist'].median())
df['hip'] = df['hip'].fillna(df['hip'].median())
df['ratio'] = df['ratio'].fillna(df['ratio'].median())
df['chol'] = df['chol'].fillna(df['chol'].median())
df['bp.1s'] = df['bp.1s'].fillna(df['bp.1s'].median())
df['bp.1d'] = df['bp.1d'].fillna(df['bp.1d'].median())
df['frame'] = df['frame'].fillna(df['frame'].mode()[0])

In [9]:
df.isnull().sum()

chol         0
stab.glu     0
hdl          0
ratio        0
glyhb       13
age          0
gender       0
height       0
weight       0
frame        0
bp.1s        0
bp.1d        0
waist        0
hip          0
fasting      0
dtype: int64

In [10]:
df = df.dropna(subset=['glyhb'])

In [11]:
df['diabetic'] = (df['glyhb'] >= 5.7).astype(int)

In [12]:
df['gender'] = (df['gender'] == 'male').astype(int)

In [13]:
df = pd.get_dummies(df, columns=['frame'], drop_first=True, dtype=int)

In [14]:
df.head()

,chol,stab.glu,hdl,ratio,glyhb,age,gender,height,weight,bp.1s,bp.1d,waist,hip,fasting,diabetic,frame_medium,frame_small
0,203.0,82,56.0,3.6,4.31,46,0,62.0,121.0,118.0,59.0,29.0,38.0,1,0,1,0
1,165.0,97,24.0,6.9,4.44,29,0,64.0,218.0,112.0,68.0,46.0,48.0,0,0,0,0
2,228.0,92,37.0,6.2,4.64,58,0,61.0,256.0,190.0,92.0,49.0,57.0,0,0,0,0
3,78.0,93,12.0,6.5,4.63,67,1,67.0,119.0,110.0,50.0,33.0,38.0,1,0,0,0
4,249.0,90,28.0,8.9,7.72,64,1,68.0,183.0,138.0,80.0,44.0,41.0,0,1,1,0

In [15]:
df['whr'] = df['waist'] / df['hip']
df['glucose_fasting_interaction'] = df['stab.glu'] * df['fasting']
df['chol_ratio_interaction'] = df['chol'] * df['ratio']
df['age_waist_interaction'] = df['age'] * df['waist']
df['bmi'] = (df['weight'] / (df['height'] ** 2)) * 703

In [16]:
X_d = df.drop(columns=['diabetic', 'glyhb'])
y_d = df['diabetic']

In [17]:
from sklearn.feature_selection import mutual_info_classif
mi_scores = mutual_info_classif(X_d, y_d)
mi_df = pd.Series(mi_scores, index=X_d.columns).sort_values(ascending=False)
print(mi_df)

stab.glu                       0.231431
glucose_fasting_interaction    0.112285
age_waist_interaction          0.100615
age                            0.065802
ratio                          0.063841
whr                            0.052210
hip                            0.045164
bp.1s                          0.042197
gender                         0.037996
waist                          0.028877
chol_ratio_interaction         0.020799
frame_medium                   0.017350
weight                         0.015709
frame_small                    0.010784
bp.1d                          0.007548
height                         0.005970
hdl                            0.000000
chol                           0.000000
fasting                        0.000000
bmi                            0.000000
dtype: float64

In [18]:
final_features = ['stab.glu', 'age_waist_interaction', 'glucose_fasting_interaction', 
                   'age', 'ratio', 'whr', 'bp.1s', 'hip', 'waist', 'height', 'hdl', 
                   'fasting', 'bp.1d']

X_d = df[final_features]
y_d = df['diabetic']

In [19]:
df_h = pd.read_csv('heart_cleveland_upload.csv')

In [20]:
df_h.isnull().sum()

age          0
sex          0
cp           0
trestbps     0
chol         0
fbs          0
restecg      0
thalach      0
exang        0
oldpeak      0
slope        0
ca           0
thal         0
condition    0
dtype: int64

In [21]:
X_h = df_h.drop(columns=['condition'])
y_h = df_h['condition']

In [22]:
df_k = pd.read_csv('ckd-dataset-v2.csv')

In [23]:
df_k.info()

<class 'pandas.DataFrame'>
RangeIndex: 202 entries, 0 to 201
Data columns (total 29 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   bp (Diastolic)  201 non-null    str
 1   bp limit        201 non-null    str
 2   sg              201 non-null    str
 3   al              201 non-null    str
 4   class           201 non-null    str
 5   rbc             201 non-null    str
 6   su              201 non-null    str
 7   pc              201 non-null    str
 8   pcc             201 non-null    str
 9   ba              201 non-null    str
 10  bgr             201 non-null    str
 11  bu              201 non-null    str
 12  sod             201 non-null    str
 13  sc              201 non-null    str
 14  pot             201 non-null    str
 15  hemo            201 non-null    str
 16  pcv             201 non-null    str
 17  rbcc            201 non-null    str
 18  wbcc            201 non-null    str
 19  htn             201 non-null    str
 20  dm              201 non-null    str
 21  cad             201 non-null    str
 22  appet           201 non-null    str
 23  pe              201 non-null    str
 24  ane             201 non-null    str
 25  grf             201 non-null    str
 26  stage           201 non-null    str
 27  affected        202 non-null    str
 28  age             202 non-null    str
dtypes: str(29)
memory usage: 74.1 KB

In [24]:
import re

df_k = df_k.iloc[2:].reset_index(drop=True)  # drop metadata rows

def convert_range(val):
    if pd.isna(val):
        return None
    val = str(val).strip()
    if val.startswith('≥') or val.startswith('>='):
        return float(re.sub(r'[≥>=]', '', val).strip())
    if val.startswith('<'):
        return float(val.replace('<', '').strip())
    if '-' in val:
        parts = val.split('-')
        try:
            return (float(parts[0].strip()) + float(parts[1].strip())) / 2
        except:
            return None
    try:
        return float(val)
    except:
        return None

range_cols = ['sg','al','su','bgr','bu','sod','sc','pot','hemo','pcv','rbcc','wbcc','grf','age']
for col in range_cols:
    df_k[col] = df_k[col].apply(convert_range)

# target
df_k['diagnosis'] = (df_k['class'].str.strip() == 'ckd').astype(int)

# drop leakage-risk columns
df_k = df_k.drop(columns=['class', 'grf', 'stage', 'affected'])

# convert remaining binary columns to int
binary_cols = ['bp (Diastolic)','bp limit','rbc','pc','pcc','ba','htn','dm','cad','appet','pe','ane']
for col in binary_cols:
    df_k[col] = df_k[col].astype(int)

# sanity checks
print(df_k.shape)
print(df_k.isna().sum().sum(), 'missing values')
print(df_k['diagnosis'].value_counts())
print(df_k.dtypes)

(200, 26)
0 missing values
diagnosis
1    128
0     72
Name: count, dtype: int64
bp (Diastolic)      int64
bp limit            int64
sg                float64
al                float64
rbc                 int64
su                float64
pc                  int64
pcc                 int64
ba                  int64
bgr               float64
bu                float64
sod               float64
sc                float64
pot               float64
hemo              float64
pcv               float64
rbcc              float64
wbcc              float64
htn                 int64
dm                  int64
cad                 int64
appet               int64
pe                  int64
ane                 int64
age               float64
diagnosis           int64
dtype: object

In [25]:
df_k.head()

,bp (Diastolic),bp limit,sg,al,rbc,su,pc,pcc,ba,bgr,...,rbcc,wbcc,htn,dm,cad,appet,pe,ane,age,diagnosis
0,0,0,1.020,1.0,0,0.0,0,0,0,112.0,...,4.755,8550.0,0,0,0,0,0,0,12.0,1
1,0,0,1.010,0.0,0,0.0,0,0,0,133.0,...,4.755,13310.0,0,0,0,0,0,0,12.0,1
2,0,0,1.010,4.0,1,0.0,1,0,1,112.0,...,4.755,15690.0,0,0,0,1,0,0,12.0,1
3,1,1,1.010,3.0,0,0.0,0,0,0,133.0,...,4.755,8550.0,0,0,0,0,0,0,12.0,1
4,0,0,1.016,0.0,0,0.0,0,0,0,175.0,...,5.345,8550.0,0,1,0,1,1,0,16.0,1

In [26]:
df_k.isnull().sum()

bp (Diastolic)    0
bp limit          0
sg                0
al                0
rbc               0
su                0
pc                0
pcc               0
ba                0
bgr               0
bu                0
sod               0
sc                0
pot               0
hemo              0
pcv               0
rbcc              0
wbcc              0
htn               0
dm                0
cad               0
appet             0
pe                0
ane               0
age               0
diagnosis         0
dtype: int64

In [27]:
df_k.head()

,bp (Diastolic),bp limit,sg,al,rbc,su,pc,pcc,ba,bgr,...,rbcc,wbcc,htn,dm,cad,appet,pe,ane,age,diagnosis
0,0,0,1.020,1.0,0,0.0,0,0,0,112.0,...,4.755,8550.0,0,0,0,0,0,0,12.0,1
1,0,0,1.010,0.0,0,0.0,0,0,0,133.0,...,4.755,13310.0,0,0,0,0,0,0,12.0,1
2,0,0,1.010,4.0,1,0.0,1,0,1,112.0,...,4.755,15690.0,0,0,0,1,0,0,12.0,1
3,1,1,1.010,3.0,0,0.0,0,0,0,133.0,...,4.755,8550.0,0,0,0,0,0,0,12.0,1
4,0,0,1.016,0.0,0,0.0,0,0,0,175.0,...,5.345,8550.0,0,1,0,1,1,0,16.0,1

In [28]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report,confusion_matrix
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC

In [29]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV

## diabetes rf

In [30]:
X_train_d,X_test_d,y_train_d,y_test_d = train_test_split(X_d,y_d,test_size=0.3,stratify=y_d,random_state = 42)

In [31]:
rf = RandomForestClassifier(class_weight='balanced',random_state=42)
params = {'n_estimators':[100,150,200,250,300],'criterion':['gini', 'entropy', 'log_loss'],'ccp_alpha':[0.0, 0.001, 0.005, 0.01, 0.02]}
grid_d = GridSearchCV(estimator=rf,param_grid=params,scoring='recall',cv=5)

In [32]:
grid_d.fit(X_train_d,y_train_d)

GridSearchCV(cv=5,
             estimator=RandomForestClassifier(class_weight='balanced',
                                              random_state=42),
             param_grid={'ccp_alpha': [0.0, 0.001, 0.005, 0.01, 0.02],
                         'criterion': ['gini', 'entropy', 'log_loss'],
                         'n_estimators': [100, 150, 200, 250, 300]},
             scoring='recall')

In [33]:
grid_d.best_params_

{'ccp_alpha': 0.02, 'criterion': 'gini', 'n_estimators': 250}

In [34]:
y_pred_d = grid_d.predict(X_test_d)

In [35]:
print(accuracy_score(y_test_d, y_pred_d))
print(confusion_matrix(y_test_d, y_pred_d))   
print(classification_report(y_test_d, y_pred_d))

0.8632478632478633
[[80 10]
 [ 6 21]]
              precision    recall  f1-score   support

           0       0.93      0.89      0.91        90
           1       0.68      0.78      0.72        27

    accuracy                           0.86       117
   macro avg       0.80      0.83      0.82       117
weighted avg       0.87      0.86      0.87       117

In [36]:
from sklearn.metrics import precision_recall_curve
import pandas as pd

rf_probs_d = grid_d.predict_proba(X_test_d)[:, 1]  # unscaled, matching how you trained it

print("RF probs range:", rf_probs_d.min(), rf_probs_d.max())  # sanity check first

precisions, recalls, thresholds = precision_recall_curve(y_test_d, rf_probs_d)

df_thresh_rf_d = pd.DataFrame({
    'threshold': thresholds,
    'precision': precisions[:-1],
    'recall': recalls[:-1]
})

print(df_thresh_rf_d[df_thresh_rf_d['precision'] >= 0.70].sort_values('recall', ascending=False).head(20))

RF probs range: 0.07144773019438871 0.8963762636071823
     threshold  precision    recall
87    0.512264   0.700000  0.777778
88    0.518114   0.724138  0.777778
89    0.522937   0.750000  0.777778
90    0.524195   0.740741  0.740741
91    0.524366   0.769231  0.740741
92    0.538954   0.800000  0.740741
93    0.541632   0.791667  0.703704
94    0.544277   0.826087  0.703704
95    0.569438   0.818182  0.666667
96    0.583976   0.857143  0.666667
97    0.608646   0.850000  0.629630
98    0.626320   0.894737  0.629630
99    0.642396   0.888889  0.592593
100   0.654584   0.882353  0.555556
101   0.670017   0.875000  0.518519
102   0.706668   0.866667  0.481481
103   0.721240   0.857143  0.444444
104   0.737898   0.846154  0.407407
105   0.757956   0.833333  0.370370
106   0.781536   0.909091  0.370370

In [37]:
rf_threshold_d = 0.539

stage1_confident_d = (rf_probs_d >= rf_threshold_d).astype(int)
print("Resolved at Stage 1:", stage1_confident_d.sum(), f"({stage1_confident_d.sum()/len(y_test_d)*100:.1f}%)")

from sklearn.metrics import precision_score, recall_score, confusion_matrix
test_preds_check = (rf_probs_d >= rf_threshold_d).astype(int)
print("Precision:", precision_score(y_test_d, test_preds_check))
print("Recall:", recall_score(y_test_d, test_preds_check))

Resolved at Stage 1: 24 (20.5%)
Precision: 0.7916666666666666
Recall: 0.7037037037037037

In [38]:
from sklearn.model_selection import cross_val_score
cv_scores_rf_d = cross_val_score(grid_d.best_estimator_, X_train_d, y_train_d, cv=5, scoring='recall')
print(cv_scores_rf_d.mean(), cv_scores_rf_d.std())

0.7256410256410256 0.1514449362137918

In [39]:
import joblib
import json

joblib.dump(grid_d.best_estimator_, 'diabetes_rf.pkl')

with open('diabetes_thresholds.json', 'r') as f:
    thresholds_d = json.load(f)
thresholds_d['rf'] = 0.539
with open('diabetes_thresholds.json', 'w') as f:
    json.dump(thresholds_d, f)

## heart knn

In [40]:
knn_h = KNeighborsClassifier()
X_train_h,X_test_h,y_train_h,y_test_h = train_test_split(X_h,y_h,test_size=0.3,stratify=y_h,random_state = 42)

In [41]:
params_h = {'n_neighbors':[5,6,7,8],'weights': ['uniform','distance'],'algorithm':['auto', 'ball_tree', 'kd_tree', 'brute'],'p':[1,2]}
scaler_h = StandardScaler()
X_train_sh = scaler_h.fit_transform(X_train_h)
X_test_sh = scaler_h.transform(X_test_h)

In [42]:
grid_hk = GridSearchCV(estimator = knn_h,param_grid=params_h,scoring='recall',cv=5)
grid_hk.fit(X_train_sh,y_train_h)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [5, 6, 7, 8], 'p': [1, 2],
                         'weights': ['uniform', 'distance']},
             scoring='recall')

In [43]:
grid_hk.best_params_

{'algorithm': 'auto', 'n_neighbors': 8, 'p': 1, 'weights': 'distance'}

In [44]:
y_pred_hk = grid_hk.predict(X_test_sh)

In [45]:
print(accuracy_score(y_test_h, y_pred_hk))
print(classification_report(y_test_h, y_pred_hk))
print(confusion_matrix(y_test_h, y_pred_hk))

0.8555555555555555
              precision    recall  f1-score   support

           0       0.81      0.96      0.88        48
           1       0.94      0.74      0.83        42

    accuracy                           0.86        90
   macro avg       0.87      0.85      0.85        90
weighted avg       0.87      0.86      0.85        90

[[46  2]
 [11 31]]

In [46]:
from sklearn.metrics import precision_recall_curve
import pandas as pd

# Get probabilities from your tuned KNN model
knn_probs = grid_hk.predict_proba(X_test_sh)[:, 1]  # probability of class 1 (disease)

# Build the precision-recall curve
precisions, recalls, thresholds = precision_recall_curve(y_test_h, knn_probs)

df_thresh_knn = pd.DataFrame({
    'threshold': thresholds,
    'precision': precisions[:-1],
    'recall': recalls[:-1]
})

# Since Stage 2 favors recall, look for thresholds that boost recall
# (lower threshold than 0.5 typically increases recall, at some precision cost)
print(df_thresh_knn.sort_values('recall', ascending=False).head(60))

    threshold  precision    recall
0    0.000000   0.466667  1.000000
1    0.092699   0.567568  1.000000
2    0.109162   0.575342  1.000000
3    0.110635   0.583333  1.000000
4    0.116462   0.591549  1.000000
5    0.116564   0.600000  1.000000
6    0.116962   0.608696  1.000000
7    0.117545   0.617647  1.000000
8    0.119913   0.626866  1.000000
9    0.120029   0.636364  1.000000
10   0.121483   0.646154  1.000000
11   0.125667   0.640625  0.976190
12   0.136998   0.650794  0.976190
13   0.142221   0.661290  0.976190
14   0.144943   0.672131  0.976190
15   0.147270   0.683333  0.976190
16   0.166738   0.694915  0.976190
17   0.186894   0.706897  0.976190
18   0.208137   0.701754  0.952381
19   0.216653   0.714286  0.952381
20   0.223677   0.727273  0.952381
21   0.224391   0.740741  0.952381
22   0.226910   0.754717  0.952381
23   0.229355   0.750000  0.928571
24   0.237115   0.764706  0.928571
25   0.237486   0.760000  0.904762
26   0.250379   0.755102  0.880952
27   0.251287   0.770833  0.880952
28   0.255093   0.787234  0.880952
29   0.257268   0.804348  0.880952
30   0.257679   0.822222  0.880952
31   0.273705   0.818182  0.857143
32   0.276231   0.837209  0.857143
33   0.281665   0.857143  0.857143
34   0.282015   0.878049  0.857143
35   0.303905   0.900000  0.857143
36   0.330619   0.897436  0.833333
37   0.351957   0.894737  0.809524
38   0.372536   0.918919  0.809524
39   0.382537   0.916667  0.785714
40   0.400800   0.914286  0.761905
41   0.460165   0.941176  0.761905
42   0.518269   0.939394  0.738095
43   0.518482   0.937500  0.714286
44   0.651046   0.967742  0.714286
45   0.658682   0.966667  0.690476
46   0.670661   0.965517  0.666667
47   0.727569   0.964286  0.642857
48   0.733154   0.962963  0.619048
49   0.742390   0.961538  0.595238
50   0.751989   0.960000  0.571429
51   0.756912   0.958333  0.547619
52   0.760505   0.956522  0.523810
53   0.769477   0.954545  0.500000
54   0.773273   1.000000  0.500000
55   0.777671   1.000000  0.476190
56   0.793432   1.000000  0.452381
57   0.840969   1.000000  0.428571
58   0.845249   1.000000  0.404762
59   0.851707   1.000000  0.380952

In [47]:

print(df_thresh_knn[df_thresh_knn['recall'] >= 0.85].sort_values('precision', ascending=False))

    threshold  precision    recall
35   0.303905   0.900000  0.857143
34   0.282015   0.878049  0.857143
33   0.281665   0.857143  0.857143
32   0.276231   0.837209  0.857143
30   0.257679   0.822222  0.880952
31   0.273705   0.818182  0.857143
29   0.257268   0.804348  0.880952
28   0.255093   0.787234  0.880952
27   0.251287   0.770833  0.880952
24   0.237115   0.764706  0.928571
25   0.237486   0.760000  0.904762
26   0.250379   0.755102  0.880952
22   0.226910   0.754717  0.952381
23   0.229355   0.750000  0.928571
21   0.224391   0.740741  0.952381
20   0.223677   0.727273  0.952381
19   0.216653   0.714286  0.952381
17   0.186894   0.706897  0.976190
18   0.208137   0.701754  0.952381
16   0.166738   0.694915  0.976190
15   0.147270   0.683333  0.976190
14   0.144943   0.672131  0.976190
13   0.142221   0.661290  0.976190
12   0.136998   0.650794  0.976190
10   0.121483   0.646154  1.000000
11   0.125667   0.640625  0.976190
9    0.120029   0.636364  1.000000
8    0.119913   0.626866  1.000000
7    0.117545   0.617647  1.000000
6    0.116962   0.608696  1.000000
5    0.116564   0.600000  1.000000
4    0.116462   0.591549  1.000000
3    0.110635   0.583333  1.000000
2    0.109162   0.575342  1.000000
1    0.092699   0.567568  1.000000
0    0.000000   0.466667  1.000000

In [48]:
knn_threshold = 0.282015 

knn_preds_custom = (knn_probs >= knn_threshold).astype(int)

from sklearn.metrics import precision_score, recall_score, confusion_matrix

print("Precision:", precision_score(y_test_h, knn_preds_custom))
print("Recall:", recall_score(y_test_h, knn_preds_custom))
print(classification_report(y_test_h, knn_preds_custom))

Precision: 0.9
Recall: 0.8571428571428571
              precision    recall  f1-score   support

           0       0.88      0.92      0.90        48
           1       0.90      0.86      0.88        42

    accuracy                           0.89        90
   macro avg       0.89      0.89      0.89        90
weighted avg       0.89      0.89      0.89        90

In [49]:
knn_train_probs = grid_hk.predict_proba(X_train_sh)[:, 1]
knn_train_preds = (knn_train_probs >= 0.29).astype(int)

print("Train recall:", recall_score(y_train_h, knn_train_preds))
print("Train precision:", precision_score(y_train_h, knn_train_preds))

Train recall: 1.0
Train precision: 1.0

In [50]:
from sklearn.model_selection import cross_val_score
cv_scores = cross_val_score(grid_hk.best_estimator_, X_train_sh, y_train_h, cv=5, scoring='recall')
print(cv_scores.mean(), cv_scores.std())

0.7789473684210526 0.0773523076668372

In [51]:
import joblib
joblib.dump(grid_hk.best_estimator_, 'heart_knn.pkl')
joblib.dump(scaler_h, 'heart_scaler.pkl')

['heart_scaler.pkl']

In [52]:
import json
thresholds = {'knn': 0.29}
with open('heart_thresholds.json', 'w') as f:
    json.dump(thresholds, f)

In [53]:
with open('heart_thresholds.json', 'r') as f:
    thresholds = json.load(f)
thresholds['svm'] = 0.33  
thresholds['nb'] = 0.40   
with open('heart_thresholds.json', 'w') as f:
    json.dump(thresholds, f)

## heart svc

In [54]:
svc_h = SVC(probability=True, random_state=42)
param_hs = {'C':[1.0,1.5,2,2.5,3,3.5],'kernel':['linear', 'poly', 'rbf', 'sigmoid'],'gamma':['scale', 'auto', float],'class_weight':['balanced']}

In [55]:
grid_hs = GridSearchCV(estimator = svc_h,param_grid=param_hs,scoring='recall',cv=5)

In [56]:
grid_hs.fit(X_train_sh,y_train_h)

C:\Users\wilso\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_validation.py:490: FitFailedWarning:
120 fits failed out of a total of 360.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
120 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\wilso\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wilso\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\base.py", line 1329, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\wilso\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\base.py", line 492, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\wilso\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'gamma' parameter of SVC must be a str among {'scale', 'auto'} or a float in the range [0.0, inf). Got <class 'float'> instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\wilso\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_search.py:1137: UserWarning: One or more of the test scores are non-finite: [0.76842105 0.76842105 0.78947368 0.8        0.76842105 0.76842105
 0.78947368 0.8               nan        nan        nan        nan
 0.76842105 0.78947368 0.78947368 0.8        0.76842105 0.78947368
 0.78947368 0.8               nan        nan        nan        nan
 0.76842105 0.77894737 0.77894737 0.8        0.76842105 0.77894737
 0.77894737 0.8               nan        nan        nan        nan
 0.76842105 0.77894737 0.75789474 0.8        0.76842105 0.76842105
 0.75789474 0.8               nan        nan        nan        nan
 0.76842105 0.75789474 0.76842105 0.78947368 0.76842105 0.75789474
 0.76842105 0.81052632        nan        nan        nan        nan
 0.76842105 0.74736842 0.75789474 0.82105263 0.76842105 0.75789474
 0.75789474 0.81052632        nan        nan        nan        nan]
  warnings.warn(

GridSearchCV(cv=5, estimator=SVC(probability=True, random_state=42),
             param_grid={'C': [1.0, 1.5, 2, 2.5, 3, 3.5],
                         'class_weight': ['balanced'],
                         'gamma': ['scale', 'auto', <class 'float'>],
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']},
             scoring='recall')

In [57]:
grid_hs.best_params_

{'C': 3.5, 'class_weight': 'balanced', 'gamma': 'scale', 'kernel': 'sigmoid'}

In [58]:
y_pred_hs = grid_hs.predict(X_test_sh)

In [59]:
print(accuracy_score(y_test_h, y_pred_hs))
print(classification_report(y_test_h, y_pred_hs))
print(confusion_matrix(y_test_h, y_pred_hs))

0.8333333333333334
              precision    recall  f1-score   support

           0       0.84      0.85      0.85        48
           1       0.83      0.81      0.82        42

    accuracy                           0.83        90
   macro avg       0.83      0.83      0.83        90
weighted avg       0.83      0.83      0.83        90

[[41  7]
 [ 8 34]]

In [60]:
from sklearn.metrics import precision_recall_curve
import pandas as pd

# Fit (if not already done)
grid_hs.fit(X_train_sh, y_train_h)

# Get probabilities from the tuned SVM
svm_probs = grid_hs.predict_proba(X_test_sh)[:, 1]  # probability of class 1 (disease)

# Build precision-recall curve
precisions, recalls, thresholds = precision_recall_curve(y_test_h, svm_probs)

df_thresh_svm = pd.DataFrame({
    'threshold': thresholds,
    'precision': precisions[:-1],
    'recall': recalls[:-1]
})

# Since SVM is part of Stage 2 (recall-focused), look for high-recall thresholds
print(df_thresh_svm[df_thresh_svm['recall'] >= 0.85].sort_values('precision', ascending=False))

    threshold  precision    recall
46   0.409373   0.840909  0.880952
47   0.417566   0.837209  0.857143
45   0.377870   0.822222  0.880952
44   0.371993   0.804348  0.880952
43   0.365060   0.787234  0.880952
40   0.320204   0.780000  0.928571
41   0.330508   0.775510  0.904762
42   0.345300   0.770833  0.880952
39   0.316436   0.764706  0.928571
38   0.315305   0.750000  0.928571
36   0.303570   0.740741  0.952381
37   0.310621   0.735849  0.928571
35   0.302899   0.727273  0.952381
34   0.300629   0.714286  0.952381
33   0.278291   0.701754  0.952381
31   0.271278   0.694915  0.976190
32   0.273615   0.689655  0.952381
30   0.263965   0.683333  0.976190
29   0.256713   0.672131  0.976190
28   0.250813   0.661290  0.976190
27   0.250519   0.650794  0.976190
26   0.241689   0.640625  0.976190
25   0.235762   0.630769  0.976190
24   0.233804   0.621212  0.976190
22   0.220369   0.617647  1.000000
23   0.228442   0.611940  0.976190
21   0.217171   0.608696  1.000000
20   0.209843   0.600000  1.000000
19   0.200579   0.591549  1.000000
18   0.197292   0.583333  1.000000
17   0.185188   0.575342  1.000000
16   0.184045   0.567568  1.000000
15   0.170470   0.560000  1.000000
14   0.169636   0.552632  1.000000
13   0.157229   0.545455  1.000000
12   0.155266   0.538462  1.000000
11   0.153809   0.531646  1.000000
10   0.153358   0.525000  1.000000
9    0.141579   0.518519  1.000000
8    0.131643   0.512195  1.000000
7    0.116686   0.506024  1.000000
6    0.112439   0.500000  1.000000
5    0.100132   0.494118  1.000000
4    0.098378   0.488372  1.000000
3    0.097466   0.482759  1.000000
2    0.086637   0.477273  1.000000
1    0.085547   0.471910  1.000000
0    0.067100   0.466667  1.000000

C:\Users\wilso\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_validation.py:490: FitFailedWarning:
120 fits failed out of a total of 360.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
120 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\wilso\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wilso\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\base.py", line 1329, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\wilso\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\base.py", line 492, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\wilso\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'gamma' parameter of SVC must be a str among {'scale', 'auto'} or a float in the range [0.0, inf). Got <class 'float'> instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\wilso\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_search.py:1137: UserWarning: One or more of the test scores are non-finite: [0.76842105 0.76842105 0.78947368 0.8        0.76842105 0.76842105
 0.78947368 0.8               nan        nan        nan        nan
 0.76842105 0.78947368 0.78947368 0.8        0.76842105 0.78947368
 0.78947368 0.8               nan        nan        nan        nan
 0.76842105 0.77894737 0.77894737 0.8        0.76842105 0.77894737
 0.77894737 0.8               nan        nan        nan        nan
 0.76842105 0.77894737 0.75789474 0.8        0.76842105 0.76842105
 0.75789474 0.8               nan        nan        nan        nan
 0.76842105 0.75789474 0.76842105 0.78947368 0.76842105 0.75789474
 0.76842105 0.81052632        nan        nan        nan        nan
 0.76842105 0.74736842 0.75789474 0.82105263 0.76842105 0.75789474
 0.75789474 0.81052632        nan        nan        nan        nan]
  warnings.warn(

In [61]:
svm_threshold = 0.40

svm_preds_custom = (svm_probs >= svm_threshold).astype(int)

from sklearn.metrics import precision_score, recall_score, confusion_matrix

print("Precision:", precision_score(y_test_h, svm_preds_custom))
print("Recall:", recall_score(y_test_h, svm_preds_custom))
print(confusion_matrix(y_test_h, svm_preds_custom))

Precision: 0.8409090909090909
Recall: 0.8809523809523809
[[41  7]
 [ 5 37]]

In [62]:
from sklearn.model_selection import cross_val_score
cv_scores = cross_val_score(grid_hs.best_estimator_, X_train_sh, y_train_h, cv=5, scoring='recall')
print(cv_scores.mean(), cv_scores.std())

0.8210526315789473 0.07877173445839876

In [63]:
joblib.dump(grid_hs.best_estimator_, 'heart_svm.pkl')

with open('heart_thresholds.json', 'r') as f:
    thresholds = json.load(f)
thresholds['svm'] = 0.41
with open('heart_thresholds.json', 'w') as f:
    json.dump(thresholds, f)

## heart naive bayes

In [64]:
gnb_h = GaussianNB()
param_hn = {'var_smoothing': [1e-9, 1e-8, 1e-7, 1e-6, 1e-5]}

In [65]:
grid_hn = GridSearchCV(estimator=gnb_h, param_grid=param_hn, scoring='recall', cv=5)

In [66]:
grid_hn.fit(X_train_h, y_train_h)

GridSearchCV(cv=5, estimator=GaussianNB(),
             param_grid={'var_smoothing': [1e-09, 1e-08, 1e-07, 1e-06, 1e-05]},
             scoring='recall')

In [67]:
grid_hn.best_params_

{'var_smoothing': 1e-09}

In [68]:
y_pred_hn = grid_hn.predict(X_test_h)

In [69]:
print(accuracy_score(y_test_h, y_pred_hn))
print(classification_report(y_test_h, y_pred_hn))
print(confusion_matrix(y_test_h, y_pred_hn))

0.8666666666666667
              precision    recall  f1-score   support

           0       0.82      0.96      0.88        48
           1       0.94      0.76      0.84        42

    accuracy                           0.87        90
   macro avg       0.88      0.86      0.86        90
weighted avg       0.88      0.87      0.86        90

[[46  2]
 [10 32]]

In [70]:
from sklearn.metrics import precision_recall_curve
import pandas as pd

nb_probs = grid_hn.predict_proba(X_test_h)[:, 1]

precisions, recalls, thresholds = precision_recall_curve(y_test_h, nb_probs)

df_thresh_nb = pd.DataFrame({
    'threshold': thresholds,
    'precision': precisions[:-1],
    'recall': recalls[:-1]
})

print(df_thresh_nb.sort_values('recall', ascending=False).head(50))

    threshold  precision    recall
0    0.000011   0.466667  1.000000
1    0.000075   0.471910  1.000000
2    0.000154   0.477273  1.000000
3    0.000249   0.482759  1.000000
4    0.000299   0.488372  1.000000
5    0.000310   0.494118  1.000000
6    0.000605   0.500000  1.000000
7    0.000629   0.506024  1.000000
8    0.000714   0.512195  1.000000
9    0.000898   0.518519  1.000000
10   0.001147   0.525000  1.000000
11   0.001519   0.531646  1.000000
12   0.001888   0.538462  1.000000
13   0.001983   0.545455  1.000000
14   0.002334   0.552632  1.000000
15   0.007715   0.560000  1.000000
16   0.007847   0.554054  0.976190
17   0.009856   0.561644  0.976190
18   0.015184   0.555556  0.952381
19   0.015725   0.563380  0.952381
20   0.020302   0.571429  0.952381
21   0.021998   0.579710  0.952381
22   0.022348   0.588235  0.952381
23   0.024337   0.582090  0.928571
24   0.025519   0.575758  0.904762
25   0.026510   0.584615  0.904762
26   0.028498   0.593750  0.904762
27   0.033407   0.603175  0.904762
28   0.034722   0.612903  0.904762
29   0.041690   0.622951  0.904762
30   0.045542   0.633333  0.904762
31   0.047891   0.644068  0.904762
32   0.066807   0.655172  0.904762
33   0.081101   0.666667  0.904762
34   0.106304   0.660714  0.880952
35   0.114193   0.672727  0.880952
36   0.120466   0.666667  0.857143
37   0.142345   0.679245  0.857143
38   0.148099   0.692308  0.857143
39   0.155229   0.705882  0.857143
40   0.156089   0.720000  0.857143
41   0.165472   0.734694  0.857143
42   0.171165   0.750000  0.857143
43   0.194272   0.765957  0.857143
44   0.210690   0.782609  0.857143
45   0.229601   0.777778  0.833333
46   0.239970   0.795455  0.833333
47   0.241534   0.790698  0.809524
48   0.254603   0.809524  0.809524
49   0.348877   0.829268  0.809524

In [71]:
nb_threshold = 0.211

nb_preds_custom = (nb_probs >= nb_threshold).astype(int)

from sklearn.metrics import precision_score, recall_score, confusion_matrix
print("Precision:", precision_score(y_test_h, nb_preds_custom))
print("Recall:", recall_score(y_test_h, nb_preds_custom))
print(confusion_matrix(y_test_h, nb_preds_custom))

Precision: 0.7777777777777778
Recall: 0.8333333333333334
[[38 10]
 [ 7 35]]

In [72]:
nb_train_probs = grid_hn.predict_proba(X_train_h)[:, 1]
nb_train_preds = (nb_train_probs >= 0.211).astype(int)

from sklearn.metrics import recall_score, precision_score

print("Train recall:", recall_score(y_train_h, nb_train_preds))
print("Train precision:", precision_score(y_train_h, nb_train_preds))

print("Test recall:", recall_score(y_test_h, nb_preds_custom))
print("Test precision:", precision_score(y_test_h, nb_preds_custom))

Train recall: 0.8631578947368421
Train precision: 0.7454545454545455
Test recall: 0.8333333333333334
Test precision: 0.7777777777777778

In [73]:

from sklearn.model_selection import cross_val_score
cv_scores = cross_val_score(grid_hn.best_estimator_, X_train_sh, y_train_h, cv=5, scoring='recall')
print(cv_scores.mean(), cv_scores.std())

0.8105263157894737 0.08551619373301012

In [74]:
knn_final = (knn_probs >= 0.29).astype(int)
svm_final = (svm_probs >= 0.41).astype(int)
nb_final = (nb_probs >= 0.211).astype(int)

stage2_combined = ((knn_final == 1) | (svm_final == 1) | (nb_final == 1)).astype(int)

from sklearn.metrics import precision_score, recall_score, confusion_matrix

print("Stage 2 combined precision:", precision_score(y_test_h, stage2_combined))
print("Stage 2 combined recall:", recall_score(y_test_h, stage2_combined))
print(confusion_matrix(y_test_h, stage2_combined))

Stage 2 combined precision: 0.7037037037037037
Stage 2 combined recall: 0.9047619047619048
[[32 16]
 [ 4 38]]

## heart rf

In [75]:
rf_h = RandomForestClassifier(class_weight='balanced',random_state=42)
params_hr = {'n_estimators':[100,150,200,250,300],'criterion':['gini', 'entropy', 'log_loss'],'ccp_alpha':[0.0, 0.001, 0.005, 0.01, 0.02]}
grid_hr = GridSearchCV(estimator=rf_h,param_grid=params_hr,scoring='recall',cv=5)

In [76]:
grid_hr.fit(X_train_sh,y_train_h)

GridSearchCV(cv=5,
             estimator=RandomForestClassifier(class_weight='balanced',
                                              random_state=42),
             param_grid={'ccp_alpha': [0.0, 0.001, 0.005, 0.01, 0.02],
                         'criterion': ['gini', 'entropy', 'log_loss'],
                         'n_estimators': [100, 150, 200, 250, 300]},
             scoring='recall')

In [77]:
grid_hr.best_params_

{'ccp_alpha': 0.02, 'criterion': 'gini', 'n_estimators': 100}

In [78]:
y_pred_hr = grid_hr.predict(X_test_sh)

In [79]:
print(accuracy_score(y_test_h, y_pred_hr))
print(classification_report(y_test_h, y_pred_hr))
print(confusion_matrix(y_test_h, y_pred_hr))

0.8222222222222222
              precision    recall  f1-score   support

           0       0.81      0.88      0.84        48
           1       0.84      0.76      0.80        42

    accuracy                           0.82        90
   macro avg       0.82      0.82      0.82        90
weighted avg       0.82      0.82      0.82        90

[[42  6]
 [10 32]]

In [80]:
from sklearn.metrics import precision_recall_curve
import pandas as pd

rf_probs_h = grid_hr.predict_proba(X_test_sh)[:, 1]

precisions, recalls, thresholds = precision_recall_curve(y_test_h, rf_probs_h)

df_thresh_rf = pd.DataFrame({
    'threshold': thresholds,
    'precision': precisions[:-1],
    'recall': recalls[:-1]
})

# Remember: RF is Stage 1, so you want HIGH PRECISION here (not recall)
# since RF's job is to confidently resolve "obvious" cases without needing Stage 2 review
print(df_thresh_rf[df_thresh_rf['precision'] >= 0.85].sort_values('recall', ascending=False))

    threshold  precision    recall
54   0.531584   0.861111  0.738095
55   0.536715   0.885714  0.738095
56   0.554377   0.882353  0.714286
57   0.589310   0.909091  0.714286
58   0.593426   0.906250  0.690476
59   0.602602   0.935484  0.690476
60   0.623381   0.966667  0.690476
61   0.625505   0.965517  0.666667
62   0.648809   0.964286  0.642857
63   0.719613   1.000000  0.642857
64   0.721790   1.000000  0.619048
65   0.742484   1.000000  0.595238
66   0.747871   1.000000  0.571429
67   0.754287   1.000000  0.547619
68   0.766138   1.000000  0.523810
69   0.766378   1.000000  0.500000
70   0.768311   1.000000  0.476190
71   0.775823   1.000000  0.452381
72   0.782756   1.000000  0.428571
73   0.785841   1.000000  0.404762
74   0.794621   1.000000  0.380952
75   0.797924   1.000000  0.357143
76   0.798698   1.000000  0.333333
77   0.802909   1.000000  0.309524
78   0.811892   1.000000  0.285714
79   0.813469   1.000000  0.261905
80   0.815637   1.000000  0.238095
81   0.855308   1.000000  0.214286
82   0.865902   1.000000  0.190476
83   0.871315   1.000000  0.166667
84   0.875105   1.000000  0.142857
85   0.881225   1.000000  0.119048
86   0.884105   1.000000  0.095238
87   0.891160   1.000000  0.071429
88   0.891421   1.000000  0.047619
89   0.895093   1.000000  0.023810

In [81]:
rf_threshold_h = 0.60

stage1_confident = (rf_probs_h >= rf_threshold_h).astype(int)
print("Cases resolved at Stage 1:", stage1_confident.sum(), f"({stage1_confident.sum()/len(y_test_h)*100:.1f}%)")

Cases resolved at Stage 1: 31 (34.4%)

In [82]:
from sklearn.model_selection import cross_val_score
cv_scores = cross_val_score(grid_hr.best_estimator_, X_train_sh, y_train_h, cv=5, scoring='recall')
print(cv_scores.mean(), cv_scores.std())

0.8315789473684211 0.0613784409983716

In [83]:
cv_scores_precision = cross_val_score(grid_hr.best_estimator_, X_train_sh, y_train_h, cv=5, scoring='precision')
print(cv_scores_precision.mean(), cv_scores_precision.std())

0.8160491469314998 0.08839611644309406

In [84]:
rf_train_probs_h = grid_hr.predict_proba(X_train_sh)[:, 1]
rf_train_preds_h = (rf_train_probs_h >= 0.72).astype(int)

from sklearn.metrics import precision_score, recall_score

print("Train precision:", precision_score(y_train_h, rf_train_preds_h))
print("Train recall:", recall_score(y_train_h, rf_train_preds_h))

rf_test_preds_h = (rf_probs_h >= 0.72).astype(int)
print("Test precision:", precision_score(y_test_h, rf_test_preds_h))
print("Test recall:", recall_score(y_test_h, rf_test_preds_h))

Train precision: 0.9629629629629629
Train recall: 0.5473684210526316
Test precision: 1.0
Test recall: 0.6190476190476191

## heart combined

In [85]:
# Majority vote instead of OR-rule for Stage 2
knn_final = (knn_probs >= 0.29).astype(int)
svm_final = (svm_probs >= 0.41).astype(int)
nb_final = (nb_probs >= 0.211).astype(int)

stage2_majority_h = ((knn_final.astype(int) + svm_final.astype(int) + nb_final.astype(int)) >= 2).astype(int)

from sklearn.metrics import precision_score, recall_score, confusion_matrix

print("Stage 2 (majority) precision:", precision_score(y_test_h, stage2_majority_h))
print("Stage 2 (majority) recall:", recall_score(y_test_h, stage2_majority_h))
print(confusion_matrix(y_test_h, stage2_majority_h))

# Combine with Stage 1 (using your chosen RF threshold, e.g. 0.72 or 0.60)
rf_threshold_h = 0.72  # or whichever you finalize
stage1_confident_h = (rf_probs_h >= rf_threshold_h).astype(int)

final_prediction_h_majority = np.where(stage1_confident_h == 1, 1, stage2_majority_h)

print("\nFull Pipeline (majority) precision:", precision_score(y_test_h, final_prediction_h_majority))
print("Full Pipeline (majority) recall:", recall_score(y_test_h, final_prediction_h_majority))
print(confusion_matrix(y_test_h, final_prediction_h_majority))
print(f"Resolved at Stage 1: {stage1_confident_h.sum()} ({stage1_confident_h.sum()/len(y_test_h)*100:.1f}%)")

Stage 2 (majority) precision: 0.9024390243902439
Stage 2 (majority) recall: 0.8809523809523809
[[44  4]
 [ 5 37]]

Full Pipeline (majority) precision: 0.9024390243902439
Full Pipeline (majority) recall: 0.8809523809523809
[[44  4]
 [ 5 37]]
Resolved at Stage 1: 26 (28.9%)

In [86]:
import joblib
import json

# Save all 4 heart disease models (only needed if not already saved)
joblib.dump(grid_hr.best_estimator_, 'heart_rf.pkl')   # adjust to your actual RF grid variable name
joblib.dump(grid_hk.best_estimator_, 'heart_knn.pkl')
joblib.dump(grid_hs.best_estimator_, 'heart_svm.pkl')
joblib.dump(grid_hn.best_estimator_, 'heart_nb.pkl')
joblib.dump(scaler_h, 'heart_scaler.pkl')  # adjust to your actual heart disease scaler variable name

# Save thresholds + combination rule used
thresholds_h = {
    'rf': 0.72,
    'knn': 0.29,
    'svm': 0.41,
    'nb': 0.211,
    'combination_rule': 'majority_vote'  # documenting which rule this disease uses
}

with open('heart_thresholds.json', 'w') as f:
    json.dump(thresholds_h, f)

print(thresholds_h)

{'rf': 0.72, 'knn': 0.29, 'svm': 0.41, 'nb': 0.211, 'combination_rule': 'majority_vote'}

In [87]:
import os
print([f for f in os.listdir() if 'heart' in f])

['heart_cleveland_upload.csv', 'heart_knn.pkl', 'heart_nb.pkl', 'heart_rf.pkl', 'heart_scaler.pkl', 'heart_svm.pkl', 'heart_thresholds.json']

## diabetes knn

In [88]:
knn_d  = KNeighborsClassifier()
params_dk= {'n_neighbors':[5,6,7,8],'weights': ['distance'],'algorithm':['auto', 'ball_tree', 'kd_tree', 'brute'],'p':[1,2]}

In [89]:
scaler = StandardScaler()
X_train_sd = scaler.fit_transform(X_train_d)
X_test_sd = scaler.transform(X_test_d)

In [90]:
grid_dk = GridSearchCV(estimator = knn_d,param_grid=params_dk,scoring='recall',cv=5)
grid_dk.fit(X_train_sd,y_train_d)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [5, 6, 7, 8], 'p': [1, 2],
                         'weights': ['distance']},
             scoring='recall')

In [91]:
grid_dk.best_params_

{'algorithm': 'auto', 'n_neighbors': 6, 'p': 2, 'weights': 'distance'}

In [92]:
y_pred_dk = grid_dk.predict(X_test_sd)

In [93]:
print(accuracy_score(y_test_d, y_pred_dk))
print(classification_report(y_test_d, y_pred_dk))
print(confusion_matrix(y_test_d, y_pred_dk))

0.8290598290598291
              precision    recall  f1-score   support

           0       0.86      0.92      0.89        90
           1       0.67      0.52      0.58        27

    accuracy                           0.83       117
   macro avg       0.77      0.72      0.74       117
weighted avg       0.82      0.83      0.82       117

[[83  7]
 [13 14]]

In [99]:
from sklearn.metrics import precision_recall_curve
import pandas as pd

# Make sure X_test_sd was generated using the correct diabetes-fitted scaler
knn_probs_d = grid_dk.predict_proba(X_test_sd)[:, 1]

precisions, recalls, thresholds = precision_recall_curve(y_test_d, knn_probs_d)

df_thresh_knn_d = pd.DataFrame({
    'threshold': thresholds,
    'precision': precisions[:-1],
    'recall': recalls[:-1]
})

print(df_thresh_knn_d.sort_values('recall', ascending=False).head(30))

    threshold  precision    recall
0    0.000000   0.230769  1.000000
1    0.136019   0.358209  0.888889
2    0.137329   0.363636  0.888889
3    0.138663   0.369231  0.888889
4    0.140019   0.375000  0.888889
5    0.140474   0.380952  0.888889
6    0.141990   0.387097  0.888889
7    0.143103   0.377049  0.851852
8    0.144915   0.366667  0.814815
9    0.145008   0.372881  0.814815
10   0.149712   0.379310  0.814815
11   0.151311   0.368421  0.777778
12   0.152553   0.375000  0.777778
13   0.154618   0.381818  0.777778
14   0.154644   0.388889  0.777778
15   0.155600   0.396226  0.777778
16   0.158148   0.403846  0.777778
17   0.158410   0.392157  0.740741
18   0.160750   0.400000  0.740741
19   0.161542   0.408163  0.740741
20   0.163028   0.395833  0.703704
21   0.163973   0.382979  0.666667
22   0.164171   0.391304  0.666667
23   0.164327   0.400000  0.666667
24   0.164946   0.409091  0.666667
25   0.165002   0.418605  0.666667
26   0.165490   0.404762  0.629630
27   0.176864   0.414634  0.629630
28   0.178192   0.425000  0.629630
29   0.185538   0.410256  0.592593

In [97]:
knn_threshold_d = 0.330  # match to your exact row's threshold

knn_preds_d = (knn_probs_d >= knn_threshold_d).astype(int)

from sklearn.metrics import precision_score, recall_score, confusion_matrix
print("Precision:", precision_score(y_test_d, knn_preds_d))
print("Recall:", recall_score(y_test_d, knn_preds_d))
print(confusion_matrix(y_test_d, knn_preds_d))

Precision: 0.5
Recall: 0.5555555555555556
[[75 15]
 [12 15]]

In [100]:
from sklearn.model_selection import cross_val_score
cv_scores_knn_d = cross_val_score(grid_dk.best_estimator_, X_train_sd, y_train_d, cv=5, scoring='recall')
print(cv_scores_knn_d.mean(), cv_scores_knn_d.std())

0.4833333333333333 0.1131986669468929

In [101]:
knn_train_probs_d = grid_dk.predict_proba(X_train_sd)[:, 1]
knn_train_preds_d = (knn_train_probs_d >= 0.218).astype(int)

from sklearn.metrics import precision_score, recall_score

print("Train precision:", precision_score(y_train_d, knn_train_preds_d))
print("Train recall:", recall_score(y_train_d, knn_train_preds_d))

print("Test precision:", precision_score(y_test_d, knn_preds_d))
print("Test recall:", recall_score(y_test_d, knn_preds_d))

Train precision: 1.0
Train recall: 1.0
Test precision: 0.5
Test recall: 0.5555555555555556

## diabetes svc

In [102]:
svc_d = SVC(probability=True, random_state=42)
param_ds = {'C':[1.0,1.5,2,2.5,3,3.5],'kernel':['linear', 'poly', 'rbf', 'sigmoid'],'gamma':['scale', 'auto', float],'class_weight':['balanced']}

In [103]:
grid_ds = GridSearchCV(estimator = svc_d,param_grid=param_ds,scoring='recall',cv=5)

In [104]:
grid_ds.fit(X_train_sd,y_train_d)

C:\Users\wilso\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_validation.py:490: FitFailedWarning:
120 fits failed out of a total of 360.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
120 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\wilso\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wilso\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\base.py", line 1329, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\wilso\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\base.py", line 492, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\wilso\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'gamma' parameter of SVC must be a str among {'scale', 'auto'} or a float in the range [0.0, inf). Got <class 'float'> instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\wilso\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_search.py:1137: UserWarning: One or more of the test scores are non-finite: [0.74102564 0.43461538 0.67435897 0.80384615 0.74102564 0.45128205
 0.67435897 0.81923077        nan        nan        nan        nan
 0.75641026 0.48333333 0.65897436 0.77051282 0.75641026 0.48333333
 0.65897436 0.8025641         nan        nan        nan        nan
 0.75641026 0.48205128 0.64358974 0.74102564 0.75641026 0.46666667
 0.64358974 0.75641026        nan        nan        nan        nan
 0.75641026 0.51538462 0.62692308 0.77307692 0.75641026 0.51538462
 0.62692308 0.74230769        nan        nan        nan        nan
 0.75641026 0.5474359  0.62692308 0.77307692 0.75641026 0.53205128
 0.62692308 0.73974359        nan        nan        nan        nan
 0.75641026 0.5474359  0.62692308 0.75769231 0.75641026 0.5474359
 0.62692308 0.75769231        nan        nan        nan        nan]
  warnings.warn(

GridSearchCV(cv=5, estimator=SVC(probability=True, random_state=42),
             param_grid={'C': [1.0, 1.5, 2, 2.5, 3, 3.5],
                         'class_weight': ['balanced'],
                         'gamma': ['scale', 'auto', <class 'float'>],
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']},
             scoring='recall')

In [105]:
grid_ds.best_params_

{'C': 1.0, 'class_weight': 'balanced', 'gamma': 'auto', 'kernel': 'sigmoid'}

In [106]:
y_pred_ds=grid_ds.predict(X_test_sd)

In [107]:
print(accuracy_score(y_test_d, y_pred_ds))
print(classification_report(y_test_d, y_pred_ds))
print(confusion_matrix(y_test_d, y_pred_ds))

0.7692307692307693
              precision    recall  f1-score   support

           0       0.94      0.74      0.83        90
           1       0.50      0.85      0.63        27

    accuracy                           0.77       117
   macro avg       0.72      0.80      0.73       117
weighted avg       0.84      0.77      0.79       117

[[67 23]
 [ 4 23]]

In [108]:
## threshold for dia svc 
from sklearn.metrics import precision_recall_curve
import pandas as pd

svm_probs_d = grid_ds.predict_proba(X_test_sd)[:, 1]

precisions, recalls, thresholds = precision_recall_curve(y_test_d, svm_probs_d)

df_thresh_svm_d = pd.DataFrame({
    'threshold': thresholds,
    'precision': precisions[:-1],
    'recall': recalls[:-1]
})

# Stage 2 model — look for a good recall/precision balance
print(df_thresh_svm_d.sort_values('recall', ascending=False).head(60))

    threshold  precision    recall
0    0.012179   0.230769  1.000000
1    0.026472   0.232759  1.000000
2    0.030390   0.234783  1.000000
3    0.032564   0.236842  1.000000
4    0.033048   0.238938  1.000000
5    0.033265   0.232143  0.962963
6    0.034686   0.234234  0.962963
7    0.035232   0.236364  0.962963
8    0.036764   0.238532  0.962963
9    0.037010   0.240741  0.962963
10   0.037100   0.242991  0.962963
11   0.042544   0.245283  0.962963
12   0.044245   0.247619  0.962963
13   0.049002   0.250000  0.962963
14   0.049655   0.252427  0.962963
15   0.053791   0.254902  0.962963
16   0.053886   0.257426  0.962963
17   0.059369   0.260000  0.962963
18   0.061743   0.262626  0.962963
19   0.063234   0.265306  0.962963
20   0.063734   0.268041  0.962963
21   0.066582   0.270833  0.962963
22   0.066843   0.273684  0.962963
23   0.068185   0.276596  0.962963
24   0.069519   0.279570  0.962963
25   0.071231   0.282609  0.962963
26   0.073211   0.285714  0.962963
27   0.075640   0.288889  0.962963
28   0.078191   0.292135  0.962963
29   0.078409   0.295455  0.962963
30   0.078835   0.298851  0.962963
31   0.080672   0.302326  0.962963
32   0.081932   0.305882  0.962963
33   0.084651   0.309524  0.962963
34   0.085997   0.301205  0.925926
35   0.086277   0.304878  0.925926
36   0.086809   0.308642  0.925926
37   0.088171   0.312500  0.925926
38   0.089581   0.316456  0.925926
39   0.100050   0.320513  0.925926
40   0.100245   0.324675  0.925926
41   0.100702   0.328947  0.925926
42   0.102864   0.333333  0.925926
43   0.106186   0.337838  0.925926
44   0.111737   0.328767  0.888889
45   0.115084   0.333333  0.888889
46   0.116275   0.338028  0.888889
47   0.117165   0.342857  0.888889
48   0.117999   0.333333  0.851852
49   0.121342   0.338235  0.851852
50   0.134586   0.343284  0.851852
51   0.135700   0.348485  0.851852
52   0.137090   0.353846  0.851852
53   0.146062   0.359375  0.851852
54   0.151675   0.365079  0.851852
55   0.151801   0.370968  0.851852
56   0.152265   0.377049  0.851852
57   0.155475   0.383333  0.851852
58   0.156681   0.389831  0.851852
59   0.168169   0.396552  0.851852

In [109]:
svm_threshold_d = 0.328

svm_preds_d = (svm_probs_d >= svm_threshold_d).astype(int)

from sklearn.metrics import precision_score, recall_score, confusion_matrix
print("Precision:", precision_score(y_test_d, svm_preds_d))
print("Recall:", recall_score(y_test_d, svm_preds_d))
print(confusion_matrix(y_test_d, svm_preds_d))

Precision: 0.6875
Recall: 0.8148148148148148
[[80 10]
 [ 5 22]]

## dia naive bayes

In [110]:
gnb_d = GaussianNB()
param_dn = {'var_smoothing': [1e-9, 1e-8, 1e-7, 1e-6, 1e-5]}

In [111]:
grid_dn = GridSearchCV(estimator=gnb_d, param_grid=param_dn, scoring='recall', cv=5)

In [112]:
grid_dn.fit(X_train_d,y_train_d)

GridSearchCV(cv=5, estimator=GaussianNB(),
             param_grid={'var_smoothing': [1e-09, 1e-08, 1e-07, 1e-06, 1e-05]},
             scoring='recall')

In [113]:
y_pred_dn=grid_dn.predict(X_test_d)

In [114]:
print(accuracy_score(y_test_d, y_pred_dn))
print(classification_report(y_test_d, y_pred_dn))
print(confusion_matrix(y_test_d, y_pred_dn))

0.8888888888888888
              precision    recall  f1-score   support

           0       0.93      0.92      0.93        90
           1       0.75      0.78      0.76        27

    accuracy                           0.89       117
   macro avg       0.84      0.85      0.85       117
weighted avg       0.89      0.89      0.89       117

[[83  7]
 [ 6 21]]

In [115]:
## threshold cv n save n pipeline 
from sklearn.metrics import precision_recall_curve
import pandas as pd

nb_probs_d = grid_dn.predict_proba(X_test_d)[:, 1]  # unscaled, matches how you trained it

precisions, recalls, thresholds = precision_recall_curve(y_test_d, nb_probs_d)

df_thresh_nb_d = pd.DataFrame({
    'threshold': thresholds,
    'precision': precisions[:-1],
    'recall': recalls[:-1]
})

print(df_thresh_nb_d.sort_values('recall', ascending=False).head(60))

    threshold  precision    recall
0    0.000004   0.230769  1.000000
1    0.000007   0.232759  1.000000
2    0.000017   0.234783  1.000000
3    0.000032   0.236842  1.000000
4    0.000037   0.238938  1.000000
5    0.000044   0.241071  1.000000
6    0.000065   0.243243  1.000000
7    0.000068   0.245455  1.000000
8    0.000071   0.247706  1.000000
9    0.000075   0.250000  1.000000
10   0.000106   0.252336  1.000000
11   0.000179   0.254717  1.000000
12   0.000215   0.257143  1.000000
13   0.000247   0.259615  1.000000
14   0.000323   0.262136  1.000000
15   0.000403   0.264706  1.000000
16   0.000467   0.267327  1.000000
17   0.000498   0.270000  1.000000
18   0.000557   0.272727  1.000000
19   0.000722   0.275510  1.000000
20   0.000770   0.278351  1.000000
21   0.000793   0.281250  1.000000
22   0.000957   0.284211  1.000000
23   0.000975   0.287234  1.000000
24   0.001006   0.279570  0.962963
25   0.001087   0.282609  0.962963
26   0.001110   0.285714  0.962963
27   0.001173   0.288889  0.962963
28   0.001244   0.292135  0.962963
29   0.001337   0.295455  0.962963
30   0.001353   0.298851  0.962963
31   0.002139   0.290698  0.925926
32   0.002689   0.294118  0.925926
33   0.002691   0.297619  0.925926
34   0.002751   0.301205  0.925926
35   0.003175   0.304878  0.925926
36   0.003361   0.308642  0.925926
37   0.003566   0.312500  0.925926
38   0.004317   0.316456  0.925926
39   0.004477   0.320513  0.925926
40   0.005018   0.324675  0.925926
41   0.005043   0.328947  0.925926
42   0.005810   0.333333  0.925926
43   0.006468   0.337838  0.925926
44   0.006820   0.342466  0.925926
45   0.006977   0.347222  0.925926
46   0.008186   0.352113  0.925926
47   0.008974   0.357143  0.925926
48   0.009695   0.347826  0.888889
49   0.010514   0.352941  0.888889
50   0.011794   0.358209  0.888889
51   0.012112   0.363636  0.888889
52   0.012706   0.369231  0.888889
53   0.017935   0.375000  0.888889
54   0.018444   0.380952  0.888889
55   0.020907   0.387097  0.888889
56   0.022351   0.393443  0.888889
57   0.024342   0.400000  0.888889
58   0.026182   0.406780  0.888889
59   0.027153   0.413793  0.888889

In [116]:
print(df_thresh_nb_d[df_thresh_nb_d['precision'] >= 0.45].sort_values('recall', ascending=False))

     threshold  precision    recall
66    0.066963   0.450980  0.851852
67    0.068047   0.460000  0.851852
68    0.072681   0.469388  0.851852
69    0.075102   0.479167  0.851852
70    0.075752   0.489362  0.851852
71    0.075763   0.500000  0.851852
72    0.079263   0.511111  0.851852
73    0.100759   0.522727  0.851852
74    0.102278   0.534884  0.851852
75    0.117451   0.547619  0.851852
76    0.118541   0.560976  0.851852
77    0.124550   0.575000  0.851852
78    0.136729   0.589744  0.851852
79    0.159201   0.605263  0.851852
80    0.163933   0.621622  0.851852
81    0.167403   0.638889  0.851852
82    0.182856   0.657143  0.851852
83    0.217337   0.676471  0.851852
84    0.350847   0.696970  0.851852
85    0.442345   0.718750  0.851852
86    0.462083   0.741935  0.851852
87    0.472557   0.733333  0.814815
88    0.481337   0.758621  0.814815
89    0.662376   0.750000  0.777778
90    0.760243   0.740741  0.740741
91    0.761115   0.769231  0.740741
92    0.769227   0.800000  0.740741
93    0.787900   0.833333  0.740741
94    0.839939   0.869565  0.740741
95    0.842809   0.863636  0.703704
96    0.861960   0.904762  0.703704
97    0.925156   0.900000  0.666667
98    0.928164   0.894737  0.629630
99    0.962986   0.888889  0.592593
100   0.973595   0.941176  0.592593
101   0.998854   1.000000  0.592593
102   0.999906   1.000000  0.555556
103   0.999920   1.000000  0.518519
104   0.999953   1.000000  0.481481
105   0.999995   1.000000  0.444444
106   0.999998   1.000000  0.407407
107   0.999999   1.000000  0.370370
108   1.000000   1.000000  0.333333
109   1.000000   1.000000  0.296296
110   1.000000   1.000000  0.259259
111   1.000000   1.000000  0.222222
112   1.000000   1.000000  0.185185
113   1.000000   1.000000  0.148148
114   1.000000   1.000000  0.111111
115   1.000000   1.000000  0.074074

In [117]:
nb_threshold_d = 0.462  # match your exact row 73 value

nb_preds_d = (nb_probs_d >= nb_threshold_d).astype(int)

from sklearn.metrics import precision_score, recall_score, confusion_matrix
print("Precision:", precision_score(y_test_d, nb_preds_d))
print("Recall:", recall_score(y_test_d, nb_preds_d))
print(confusion_matrix(y_test_d, nb_preds_d))

Precision: 0.7419354838709677
Recall: 0.8518518518518519
[[82  8]
 [ 4 23]]

In [118]:
# Cross-validation
from sklearn.model_selection import cross_val_score
cv_scores_nb_d = cross_val_score(grid_dn.best_estimator_, X_train_d, y_train_d, cv=5, scoring='recall')
print(cv_scores_nb_d.mean(), cv_scores_nb_d.std())

# Overfitting check (train vs test)
nb_train_probs_d = grid_dn.predict_proba(X_train_d)[:, 1]
nb_train_preds_d = (nb_train_probs_d >= 0.156).astype(int)

from sklearn.metrics import precision_score, recall_score
print("Train precision:", precision_score(y_train_d, nb_train_preds_d))
print("Train recall:", recall_score(y_train_d, nb_train_preds_d))
print("Test precision:", precision_score(y_test_d, nb_preds_d))
print("Test recall:", recall_score(y_test_d, nb_preds_d))

0.6423076923076924 0.1300760916237004
Train precision: 0.6024096385542169
Train recall: 0.8064516129032258
Test precision: 0.7419354838709677
Test recall: 0.8518518518518519

## kidney rf

In [119]:
X_k = df_k.drop(columns=['diagnosis'])
y_k = df_k['diagnosis']
X_train_k,X_test_k,y_train_k,y_test_k = train_test_split(X_k,y_k,test_size=0.3,stratify=y_k,random_state = 42)

In [120]:
rf_k = RandomForestClassifier(class_weight='balanced',random_state=42)
params_kr = {'n_estimators':[100,150,200,250,300],'criterion':['gini', 'entropy', 'log_loss'],'ccp_alpha':[0.0, 0.001, 0.005, 0.01, 0.02]}

In [121]:
grid_kr = GridSearchCV(estimator=rf_k,param_grid=params_kr,scoring='recall',cv=5)

In [122]:
grid_kr.fit(X_train_k,y_train_k)

GridSearchCV(cv=5,
             estimator=RandomForestClassifier(class_weight='balanced',
                                              random_state=42),
             param_grid={'ccp_alpha': [0.0, 0.001, 0.005, 0.01, 0.02],
                         'criterion': ['gini', 'entropy', 'log_loss'],
                         'n_estimators': [100, 150, 200, 250, 300]},
             scoring='recall')

In [123]:
grid_kr.best_params_

{'ccp_alpha': 0.0, 'criterion': 'gini', 'n_estimators': 100}

In [124]:
y_pred_kr = grid_kr.predict(X_test_k)

In [125]:
print(accuracy_score(y_test_k, y_pred_kr))
print(classification_report(y_test_k, y_pred_kr))
print(confusion_matrix(y_test_k, y_pred_kr))

0.9833333333333333
              precision    recall  f1-score   support

           0       0.96      1.00      0.98        22
           1       1.00      0.97      0.99        38

    accuracy                           0.98        60
   macro avg       0.98      0.99      0.98        60
weighted avg       0.98      0.98      0.98        60

[[22  0]
 [ 1 37]]

In [126]:
from sklearn.metrics import precision_recall_curve
import pandas as pd

rf_probs_k = grid_kr.predict_proba(X_test_k)[:, 1]  # adjust to your actual CKD RF variable name

precisions, recalls, thresholds = precision_recall_curve(y_test_k, rf_probs_k)

df_thresh_rf_k = pd.DataFrame({
    'threshold': thresholds,
    'precision': precisions[:-1],
    'recall': recalls[:-1]
})

print(df_thresh_rf_k[df_thresh_rf_k['precision'] >= 0.95].sort_values('recall', ascending=False))

    threshold  precision    recall
7        0.14   0.950000  1.000000
8        0.20   0.974359  1.000000
9        0.48   1.000000  1.000000
10       0.71   1.000000  0.973684
11       0.72   1.000000  0.947368
12       0.77   1.000000  0.921053
13       0.79   1.000000  0.894737
14       0.87   1.000000  0.868421
15       0.89   1.000000  0.842105
16       0.90   1.000000  0.815789
17       0.91   1.000000  0.789474
18       0.92   1.000000  0.763158
19       0.94   1.000000  0.736842
20       0.95   1.000000  0.710526
21       0.96   1.000000  0.684211
22       0.97   1.000000  0.657895
23       0.98   1.000000  0.631579
24       0.99   1.000000  0.605263
25       1.00   1.000000  0.421053

In [127]:
rf_threshold_k = 0.48

stage1_confident_k = (rf_probs_k >= rf_threshold_k).astype(int)
print("Resolved at Stage 1:", stage1_confident_k.sum(), f"({stage1_confident_k.sum()/len(y_test_k)*100:.1f}%)")

Resolved at Stage 1: 38 (63.3%)

In [128]:
from sklearn.model_selection import cross_val_score

cv_scores_rf_k = cross_val_score(grid_kr.best_estimator_, X_train_k, y_train_k, cv=5, scoring='recall')
print(cv_scores_rf_k.mean(), cv_scores_rf_k.std())

cv_scores_rf_k_prec = cross_val_score(grid_kr.best_estimator_, X_train_k, y_train_k, cv=5, scoring='precision')
print(cv_scores_rf_k_prec.mean(), cv_scores_rf_k_prec.std())

1.0 0.0
0.9894736842105264 0.02105263157894739

In [129]:
rf_train_probs_k = grid_kr.predict_proba(X_train_k)[:, 1]
rf_train_preds_k = (rf_train_probs_k >= 0.48).astype(int)

from sklearn.metrics import precision_score, recall_score

print("Train precision:", precision_score(y_train_k, rf_train_preds_k))
print("Train recall:", recall_score(y_train_k, rf_train_preds_k))

rf_probs_k = grid_kr.predict_proba(X_test_k)[:, 1]
rf_test_preds_k = (rf_probs_k >= 0.48).astype(int)

print("Test precision:", precision_score(y_test_k, rf_test_preds_k))
print("Test recall:", recall_score(y_test_k, rf_test_preds_k))

Train precision: 1.0
Train recall: 1.0
Test precision: 1.0
Test recall: 1.0

In [130]:
import joblib
import json

joblib.dump(grid_kr.best_estimator_, 'ckd_rf.pkl')

try:
    with open('ckd_thresholds.json', 'r') as f:
        thresholds_k = json.load(f)
except FileNotFoundError:
    thresholds_k = {}

thresholds_k['rf'] = 0.48

with open('ckd_thresholds.json', 'w') as f:
    json.dump(thresholds_k, f)

print(thresholds_k)

{'rf': 0.48, 'knn': 0.141, 'svm': 0.308, 'nb': 7.742932e-16, 'combination_rule': 'majority_vote'}

## Kidney KNN

In [131]:
knn_k = KNeighborsClassifier()
param_kk = {'n_neighbors':[5,6,7,8],'weights': ['distance'],'algorithm':['auto', 'ball_tree', 'kd_tree', 'brute'],'p':[1,2]}

In [132]:
scaler_k = StandardScaler()
X_train_sk = scaler_k.fit_transform(X_train_k)
X_test_sk = scaler_k.transform(X_test_k)

In [133]:
grid_kk = GridSearchCV(estimator = knn_k,param_grid=param_kk,scoring='recall',cv=5)

In [134]:
grid_kk.fit(X_train_sk,y_train_k)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'n_neighbors': [5, 6, 7, 8], 'p': [1, 2],
                         'weights': ['distance']},
             scoring='recall')

In [135]:
grid_kk.best_params_

{'algorithm': 'auto', 'n_neighbors': 5, 'p': 1, 'weights': 'distance'}

In [136]:
y_pred_kk = grid_kk.predict(X_test_sk)

In [137]:
print(accuracy_score(y_test_k, y_pred_kk))
print(classification_report(y_test_k, y_pred_kk))
print(confusion_matrix(y_test_k, y_pred_kk))

0.9333333333333333
              precision    recall  f1-score   support

           0       0.85      1.00      0.92        22
           1       1.00      0.89      0.94        38

    accuracy                           0.93        60
   macro avg       0.92      0.95      0.93        60
weighted avg       0.94      0.93      0.93        60

[[22  0]
 [ 4 34]]

In [138]:
from sklearn.metrics import precision_recall_curve
import pandas as pd

knn_probs_k = grid_kk.predict_proba(X_test_sk)[:, 1]

precisions, recalls, thresholds = precision_recall_curve(y_test_k, knn_probs_k)

df_thresh_knn_k = pd.DataFrame({
    'threshold': thresholds,
    'precision': precisions[:-1],
    'recall': recalls[:-1]
})

print(df_thresh_knn_k.sort_values('recall', ascending=False).head(20))

    threshold  precision    recall
0    0.000000   0.633333  1.000000
1    0.141209   1.000000  1.000000
2    0.190555   1.000000  0.973684
3    0.403029   1.000000  0.947368
4    0.422150   1.000000  0.921053
5    0.598194   1.000000  0.894737
6    0.641143   1.000000  0.868421
7    0.798317   1.000000  0.842105
8    0.806782   1.000000  0.815789
9    0.809578   1.000000  0.789474
10   0.818696   1.000000  0.763158
11   0.820599   1.000000  0.736842
12   0.847674   1.000000  0.710526
13   1.000000   1.000000  0.684211

In [139]:
knn_threshold_k = 0.141

knn_preds_k = (knn_probs_k >= knn_threshold_k).astype(int)

from sklearn.metrics import precision_score, recall_score, confusion_matrix
print("Precision:", precision_score(y_test_k, knn_preds_k))
print("Recall:", recall_score(y_test_k, knn_preds_k))
print(confusion_matrix(y_test_k, knn_preds_k))

Precision: 1.0
Recall: 1.0
[[22  0]
 [ 0 38]]

In [140]:
knn_train_probs_k = grid_kk.predict_proba(X_train_sk)[:, 1]
knn_train_preds_k = (knn_train_probs_k >= 0.141).astype(int)

print("Train precision:", precision_score(y_train_k, knn_train_preds_k))
print("Train recall:", recall_score(y_train_k, knn_train_preds_k))
print("Test precision:", precision_score(y_test_k, knn_preds_k))
print("Test recall:", recall_score(y_test_k, knn_preds_k))

Train precision: 1.0
Train recall: 1.0
Test precision: 1.0
Test recall: 1.0

In [141]:
from sklearn.model_selection import cross_val_score
cv_scores_knn_k = cross_val_score(grid_kk.best_estimator_, X_train_sk, y_train_k, cv=5, scoring='recall')
print(cv_scores_knn_k.mean(), cv_scores_knn_k.std())

0.9333333333333333 0.06478835438717

In [142]:
import joblib
import json

joblib.dump(grid_kk.best_estimator_, 'ckd_knn.pkl')

with open('ckd_thresholds.json', 'r') as f:
    thresholds_k = json.load(f)
thresholds_k['knn'] = 0.141
with open('ckd_thresholds.json', 'w') as f:
    json.dump(thresholds_k, f)

## kidney SVC

In [143]:
svc_k = SVC(probability=True,random_state=42)

In [144]:
params_sk = {'C':[1.0,1.5,2,2.5,3,3.5],'kernel':['linear', 'poly', 'rbf', 'sigmoid'],'gamma':['scale', 'auto', float],'class_weight':['balanced']}

In [145]:
grid_ks = GridSearchCV(estimator=svc_k, param_grid=params_sk, scoring='recall', cv=5)

In [146]:
grid_ks.fit(X_train_sk,y_train_k)

C:\Users\wilso\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_validation.py:490: FitFailedWarning:
120 fits failed out of a total of 360.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
120 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\wilso\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_validation.py", line 833, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wilso\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\base.py", line 1329, in wrapper
    estimator._validate_params()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\wilso\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\base.py", line 492, in _validate_params
    validate_parameter_constraints(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self._parameter_constraints,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.get_params(deep=False),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        caller_name=self.__class__.__name__,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\wilso\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\_param_validation.py", line 98, in validate_parameter_constraints
    raise InvalidParameterError(
    ...<2 lines>...
    )
sklearn.utils._param_validation.InvalidParameterError: The 'gamma' parameter of SVC must be a str among {'scale', 'auto'} or a float in the range [0.0, inf). Got <class 'float'> instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\wilso\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\model_selection\_search.py:1137: UserWarning: One or more of the test scores are non-finite: [0.97777778 0.82222222 0.98888889 0.98888889 0.97777778 0.8
 0.98888889 0.98888889        nan        nan        nan        nan
 0.97777778 0.92222222 0.98888889 0.98888889 0.97777778 0.92222222
 0.98888889 0.98888889        nan        nan        nan        nan
 0.97777778 0.97777778 0.98888889 0.98888889 0.97777778 0.98888889
 0.98888889 0.98888889        nan        nan        nan        nan
 0.97777778 0.98888889 0.98888889 0.98888889 0.97777778 0.98888889
 0.98888889 0.98888889        nan        nan        nan        nan
 0.97777778 1.         0.98888889 0.98888889 0.97777778 1.
 0.98888889 0.98888889        nan        nan        nan        nan
 0.97777778 1.         0.98888889 0.98888889 0.97777778 1.
 0.98888889 0.98888889        nan        nan        nan        nan]
  warnings.warn(

GridSearchCV(cv=5, estimator=SVC(probability=True, random_state=42),
             param_grid={'C': [1.0, 1.5, 2, 2.5, 3, 3.5],
                         'class_weight': ['balanced'],
                         'gamma': ['scale', 'auto', <class 'float'>],
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']},
             scoring='recall')

In [147]:
grid_ks.best_params_

{'C': 3, 'class_weight': 'balanced', 'gamma': 'scale', 'kernel': 'poly'}

In [148]:
y_pred_sk = grid_ks.predict(X_test_sk)

In [149]:
print(accuracy_score(y_test_k, y_pred_sk))
print(classification_report(y_test_k, y_pred_sk))
print(confusion_matrix(y_test_k, y_pred_sk))

0.9666666666666667
              precision    recall  f1-score   support

           0       0.92      1.00      0.96        22
           1       1.00      0.95      0.97        38

    accuracy                           0.97        60
   macro avg       0.96      0.97      0.96        60
weighted avg       0.97      0.97      0.97        60

[[22  0]
 [ 2 36]]

In [150]:
from sklearn.metrics import precision_recall_curve
import pandas as pd

svm_probs_k = grid_ks.predict_proba(X_test_sk)[:, 1]

precisions, recalls, thresholds = precision_recall_curve(y_test_k, svm_probs_k)

df_thresh_svm_k = pd.DataFrame({
    'threshold': thresholds,
    'precision': precisions[:-1],
    'recall': recalls[:-1]
})

print(df_thresh_svm_k.sort_values('recall', ascending=False).head(40))

    threshold  precision    recall
0    0.000142   0.633333  1.000000
1    0.000209   0.644068  1.000000
2    0.000238   0.655172  1.000000
3    0.000793   0.666667  1.000000
4    0.002630   0.678571  1.000000
5    0.004317   0.690909  1.000000
6    0.005017   0.703704  1.000000
7    0.005450   0.716981  1.000000
8    0.006522   0.730769  1.000000
9    0.010094   0.745098  1.000000
10   0.013840   0.760000  1.000000
11   0.014372   0.775510  1.000000
12   0.015644   0.791667  1.000000
13   0.018438   0.808511  1.000000
14   0.030819   0.826087  1.000000
15   0.043418   0.844444  1.000000
16   0.046895   0.863636  1.000000
17   0.067373   0.883721  1.000000
18   0.088269   0.904762  1.000000
19   0.221260   0.926829  1.000000
20   0.284058   0.950000  1.000000
21   0.308153   0.974359  1.000000
22   0.330412   0.973684  0.973684
23   0.524089   1.000000  0.973684
24   0.836325   1.000000  0.947368
25   0.917727   1.000000  0.921053
26   0.926014   1.000000  0.894737
27   0.929220   1.000000  0.868421
28   0.929527   1.000000  0.842105
29   0.955579   1.000000  0.815789
30   0.957082   1.000000  0.789474
31   0.958112   1.000000  0.763158
32   0.958231   1.000000  0.736842
33   0.964913   1.000000  0.710526
34   0.966166   1.000000  0.684211
35   0.968763   1.000000  0.657895
36   0.969339   1.000000  0.631579
37   0.976293   1.000000  0.605263
38   0.979139   1.000000  0.578947
39   0.982302   1.000000  0.552632

In [151]:
svm_threshold_k = 0.308

svm_preds_k = (svm_probs_k >= svm_threshold_k).astype(int)

from sklearn.metrics import precision_score, recall_score, confusion_matrix
print("Precision:", precision_score(y_test_k, svm_preds_k))
print("Recall:", recall_score(y_test_k, svm_preds_k))
print(confusion_matrix(y_test_k, svm_preds_k))

Precision: 0.9743589743589743
Recall: 1.0
[[21  1]
 [ 0 38]]

In [152]:
from sklearn.model_selection import cross_val_score
cv_scores_svm_k = cross_val_score(grid_ks.best_estimator_, X_train_sk, y_train_k, cv=5, scoring='recall')
print(cv_scores_svm_k.mean(), cv_scores_svm_k.std())

1.0 0.0

In [153]:
svm_train_probs_k = grid_ks.predict_proba(X_train_sk)[:, 1]
svm_train_preds_k = (svm_train_probs_k >= 0.308).astype(int)

print("Train precision:", precision_score(y_train_k, svm_train_preds_k))
print("Train recall:", recall_score(y_train_k, svm_train_preds_k))
print("Test precision:", precision_score(y_test_k, svm_preds_k))
print("Test recall:", recall_score(y_test_k, svm_preds_k))

Train precision: 0.989010989010989
Train recall: 1.0
Test precision: 0.9743589743589743
Test recall: 1.0

In [154]:
import joblib
import json

joblib.dump(grid_ks.best_estimator_, 'ckd_svm.pkl')

with open('ckd_thresholds.json', 'r') as f:
    thresholds_k = json.load(f)
thresholds_k['svm'] = 0.308
with open('ckd_thresholds.json', 'w') as f:
    json.dump(thresholds_k, f)

print(thresholds_k)

{'rf': 0.48, 'knn': 0.141, 'svm': 0.308, 'nb': 7.742932e-16, 'combination_rule': 'majority_vote'}

## kidney naiye bayes

In [155]:
gnb_k = GaussianNB()
params_nk = {'var_smoothing': [1e-9, 1e-8, 1e-7, 1e-6, 1e-5]}

grid_kn = GridSearchCV(estimator=gnb_k, param_grid=params_nk, scoring='recall', cv=5)
grid_kn.fit(X_train_k, y_train_k)

GridSearchCV(cv=5, estimator=GaussianNB(),
             param_grid={'var_smoothing': [1e-09, 1e-08, 1e-07, 1e-06, 1e-05]},
             scoring='recall')

In [156]:
grid_kn.best_params_

{'var_smoothing': 1e-09}

In [157]:
y_pred_kn = grid_kn.predict(X_test_k)
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test_k, y_pred_kn))
print(confusion_matrix(y_test_k, y_pred_kn))

              precision    recall  f1-score   support

           0       0.88      1.00      0.94        22
           1       1.00      0.92      0.96        38

    accuracy                           0.95        60
   macro avg       0.94      0.96      0.95        60
weighted avg       0.96      0.95      0.95        60

[[22  0]
 [ 3 35]]

In [158]:
from sklearn.metrics import precision_recall_curve
import pandas as pd

nb_probs_k = grid_kn.predict_proba(X_test_k)[:, 1]  # unscaled, matches training

precisions, recalls, thresholds = precision_recall_curve(y_test_k, nb_probs_k)

df_thresh_nb_k = pd.DataFrame({
    'threshold': thresholds,
    'precision': precisions[:-1],
    'recall': recalls[:-1]
})

print(df_thresh_nb_k.sort_values('recall', ascending=False).head(40))

       threshold  precision    recall
0   5.412335e-22   0.633333  1.000000
1   7.086630e-22   0.644068  1.000000
2   1.328373e-21   0.655172  1.000000
3   6.130430e-21   0.666667  1.000000
4   6.912270e-21   0.678571  1.000000
5   8.405685e-21   0.690909  1.000000
6   1.390202e-20   0.703704  1.000000
7   2.837101e-20   0.716981  1.000000
8   3.576527e-20   0.730769  1.000000
9   7.754581e-20   0.745098  1.000000
10  8.632374e-20   0.760000  1.000000
11  9.002995e-20   0.775510  1.000000
12  9.716799e-20   0.791667  1.000000
13  1.571072e-19   0.808511  1.000000
14  2.569423e-19   0.826087  1.000000
15  2.649043e-19   0.844444  1.000000
16  3.718477e-19   0.863636  1.000000
17  4.322166e-19   0.883721  1.000000
18  2.270518e-18   0.904762  1.000000
19  1.324310e-17   0.926829  1.000000
20  1.446075e-17   0.950000  1.000000
21  5.174017e-16   0.974359  1.000000
22  7.742932e-16   1.000000  1.000000
23  1.766636e-15   1.000000  0.973684
24  9.187158e-14   1.000000  0.947368
25  1.000000e+00   1.000000  0.921053

In [159]:

nb_threshold_k = 7.742932e-16

nb_preds_k = (nb_probs_k >= nb_threshold_k).astype(int)

from sklearn.metrics import precision_score, recall_score, confusion_matrix
print("Precision:", precision_score(y_test_k, nb_preds_k))
print("Recall:", recall_score(y_test_k, nb_preds_k))
print(confusion_matrix(y_test_k, nb_preds_k))

Precision: 1.0
Recall: 1.0
[[22  0]
 [ 0 38]]

In [160]:
from sklearn.model_selection import cross_val_score
cv_scores_nb_k = cross_val_score(grid_kn.best_estimator_, X_train_k, y_train_k, cv=5, scoring='recall')
print(cv_scores_nb_k.mean(), cv_scores_nb_k.std())

0.9444444444444443 0.03513641844631534

In [161]:
nb_train_probs_k = grid_kn.predict_proba(X_train_k)[:, 1]
nb_train_preds_k = (nb_train_probs_k >= nb_threshold_k).astype(int)

print("Train precision:", precision_score(y_train_k, nb_train_preds_k))
print("Train recall:", recall_score(y_train_k, nb_train_preds_k))

Train precision: 1.0
Train recall: 1.0

In [162]:
import joblib
import json

joblib.dump(grid_kn.best_estimator_, 'ckd_nb.pkl')

with open('ckd_thresholds.json', 'r') as f:
    thresholds_k = json.load(f)
thresholds_k['nb'] = 7.742932e-16
with open('ckd_thresholds.json', 'w') as f:
    json.dump(thresholds_k, f)

print(thresholds_k)

{'rf': 0.48, 'knn': 0.141, 'svm': 0.308, 'nb': 7.742932e-16, 'combination_rule': 'majority_vote'}

## kidney combined

In [163]:


# Majority vote instead of OR-rule for CKD's Stage 2
knn_final_k = (knn_probs_k >= 0.141).astype(int)
svm_final_k = (svm_probs_k >= 0.308).astype(int)
nb_final_k = (nb_probs_k >= 7.742932e-16).astype(int)

stage2_majority_k = ((knn_final_k.astype(int) + svm_final_k.astype(int) + nb_final_k.astype(int)) >= 2).astype(int)

print("Stage 2 (majority) precision:", precision_score(y_test_k, stage2_majority_k))
print("Stage 2 (majority) recall:", recall_score(y_test_k, stage2_majority_k))
print(confusion_matrix(y_test_k, stage2_majority_k))

# Combine with Stage 1 (RF)
rf_threshold_k = 0.48
stage1_confident_k = (rf_probs_k >= rf_threshold_k).astype(int)

final_prediction_k_majority = np.where(stage1_confident_k == 1, 1, stage2_majority_k)

print("\nFull Pipeline (majority) precision:", precision_score(y_test_k, final_prediction_k_majority))
print("Full Pipeline (majority) recall:", recall_score(y_test_k, final_prediction_k_majority))
print(confusion_matrix(y_test_k, final_prediction_k_majority))
print(f"Resolved at Stage 1: {stage1_confident_k.sum()} ({stage1_confident_k.sum()/len(y_test_k)*100:.1f}%)")

# ===== SAVE EVERYTHING =====
joblib.dump(grid_kr.best_estimator_, 'ckd_rf.pkl')
joblib.dump(grid_kk.best_estimator_, 'ckd_knn.pkl')
joblib.dump(grid_ks.best_estimator_, 'ckd_svm.pkl')
joblib.dump(grid_kn.best_estimator_, 'ckd_nb.pkl')
joblib.dump(scaler_k, 'ckd_scaler.pkl')

thresholds_k = {
    'rf': 0.48,
    'knn': 0.141,
    'svm': 0.308,
    'nb': 7.742932e-16,
    'combination_rule': 'majority_vote'
}

with open('ckd_thresholds.json', 'w') as f:
    json.dump(thresholds_k, f)

print(thresholds_k)

Stage 2 (majority) precision: 1.0
Stage 2 (majority) recall: 1.0
[[22  0]
 [ 0 38]]

Full Pipeline (majority) precision: 1.0
Full Pipeline (majority) recall: 1.0
[[22  0]
 [ 0 38]]
Resolved at Stage 1: 38 (63.3%)
{'rf': 0.48, 'knn': 0.141, 'svm': 0.308, 'nb': 7.742932e-16, 'combination_rule': 'majority_vote'}

## diabetes combined

In [164]:
from sklearn.metrics import precision_score, recall_score, confusion_matrix
import numpy as np
import joblib
import json

# Majority vote for diabetes's Stage 2
knn_final_d = (knn_probs_d >= 0.330).astype(int)
svm_final_d = (svm_probs_d >= 0.328).astype(int)
nb_final_d = (nb_probs_d >= 0.462).astype(int)

stage2_majority_d = ((knn_final_d.astype(int) + svm_final_d.astype(int) + nb_final_d.astype(int)) >= 2).astype(int)

print("Stage 2 (majority) precision:", precision_score(y_test_d, stage2_majority_d))
print("Stage 2 (majority) recall:", recall_score(y_test_d, stage2_majority_d))
print(confusion_matrix(y_test_d, stage2_majority_d))

# Combine with Stage 1 (RF)
rf_threshold_d = 0.539
stage1_confident_d = (rf_probs_d >= rf_threshold_d).astype(int)

final_prediction_d_majority = np.where(stage1_confident_d == 1, 1, stage2_majority_d)

print("\nFull Pipeline (majority) precision:", precision_score(y_test_d, final_prediction_d_majority))
print("Full Pipeline (majority) recall:", recall_score(y_test_d, final_prediction_d_majority))
print(confusion_matrix(y_test_d, final_prediction_d_majority))
print(f"Resolved at Stage 1: {stage1_confident_d.sum()} ({stage1_confident_d.sum()/len(y_test_d)*100:.1f}%)")

# ===== SAVE EVERYTHING =====
joblib.dump(grid_d.best_estimator_, 'diabetes_rf.pkl')
joblib.dump(grid_dk.best_estimator_, 'diabetes_knn.pkl')
joblib.dump(grid_ds.best_estimator_, 'diabetes_svm.pkl')
joblib.dump(grid_dn.best_estimator_, 'diabetes_nb.pkl')
joblib.dump(scaler, 'diabetes_scaler.pkl')  # adjust to your actual diabetes scaler variable name

thresholds_d = {
    'rf': 0.539,
    'knn': 0.330,
    'svm': 0.328,
    'nb': 0.462,
    'combination_rule': 'majority_vote'
}

with open('diabetes_thresholds.json', 'w') as f:
    json.dump(thresholds_d, f)

print(thresholds_d)

Stage 2 (majority) precision: 0.7586206896551724
Stage 2 (majority) recall: 0.8148148148148148
[[83  7]
 [ 5 22]]

Full Pipeline (majority) precision: 0.71875
Full Pipeline (majority) recall: 0.8518518518518519
[[81  9]
 [ 4 23]]
Resolved at Stage 1: 24 (20.5%)
{'rf': 0.539, 'knn': 0.33, 'svm': 0.328, 'nb': 0.462, 'combination_rule': 'majority_vote'}

In [165]:
import joblib
joblib.dump(scaler, 'diabetes_scaler.pkl')

['diabetes_scaler.pkl']

In [166]:
import json
with open('diabetes_thresholds.json', 'r') as f:
    print(json.load(f))

{'rf': 0.539, 'knn': 0.33, 'svm': 0.328, 'nb': 0.462, 'combination_rule': 'majority_vote'}

In [167]:


def load_disease_pipeline(disease_name):
    """Loads all models, scaler, and thresholds for a given disease."""
    models = {
        'rf': joblib.load(f'{disease_name}_rf.pkl'),
        'knn': joblib.load(f'{disease_name}_knn.pkl'),
        'svm': joblib.load(f'{disease_name}_svm.pkl'),
        'nb': joblib.load(f'{disease_name}_nb.pkl'),
    }
    scaler = joblib.load(f'{disease_name}_scaler.pkl')

    with open(f'{disease_name}_thresholds.json', 'r') as f:
        thresholds = json.load(f)

    return models, scaler, thresholds


def predict_pipeline(patient_data_raw, patient_data_scaled, models, thresholds):
    """
    patient_data_raw: unscaled features (for RF, NB) - shape (1, n_features)
    patient_data_scaled: scaled features (for KNN, SVM) - shape (1, n_features)
    """
    # Stage 1 — RF (unscaled)
    rf_proba = models['rf'].predict_proba(patient_data_raw)[0][1]

    if rf_proba >= thresholds['rf']:
        return {
            'prediction': 1,
            'confidence': rf_proba,
            'stage_used': 'Stage 1 (Random Forest)'
        }

    # Stage 2 — KNN + SVM (scaled), NB (unscaled)
    knn_proba = models['knn'].predict_proba(patient_data_scaled)[0][1]
    svm_proba = models['svm'].predict_proba(patient_data_scaled)[0][1]
    nb_proba = models['nb'].predict_proba(patient_data_raw)[0][1]

    knn_pred = int(knn_proba >= thresholds['knn'])
    svm_pred = int(svm_proba >= thresholds['svm'])
    nb_pred = int(nb_proba >= thresholds['nb'])

    votes = knn_pred + svm_pred + nb_pred
    final_pred = 1 if votes >= 2 else 0  # majority vote

    avg_confidence = (knn_proba + svm_proba + nb_proba) / 3

    return {
        'prediction': final_pred,
        'confidence': avg_confidence,
        'stage_used': 'Stage 2 (Ensemble - Majority Vote)',
        'individual_votes': {'knn': knn_pred, 'svm': svm_pred, 'nb': nb_pred}
    }

In [168]:
# Example test for CKD
models_k, scaler_k_loaded, thresholds_k_loaded = load_disease_pipeline('ckd')

sample_raw = X_test_k.iloc[[0]]        # unscaled, one row
sample_scaled = scaler_k_loaded.transform(sample_raw)  # scale it fresh

result = predict_pipeline(sample_raw, sample_scaled, models_k, thresholds_k_loaded)
print(result)
print("Actual label:", y_test_k.iloc[0])

{'prediction': 1, 'confidence': np.float64(1.0), 'stage_used': 'Stage 1 (Random Forest)'}
Actual label: 1

In [169]:
import joblib
import json

joblib.dump(grid_hr.best_estimator_, 'heart_rf.pkl')
joblib.dump(grid_hk.best_estimator_, 'heart_knn.pkl')
joblib.dump(grid_hs.best_estimator_, 'heart_svm.pkl')
joblib.dump(grid_hn.best_estimator_, 'heart_nb.pkl')
joblib.dump(scaler, 'heart_scaler.pkl')  # confirm this is heart's scaler variable

thresholds_h = {'rf': 0.72, 'knn': 0.29, 'svm': 0.41, 'nb': 0.211, 'combination_rule': 'majority_vote'}
with open('heart_thresholds.json', 'w') as f:
    json.dump(thresholds_h, f)

print("Heart disease saved.")

Heart disease saved.

In [170]:
joblib.dump(grid_d.best_estimator_, 'diabetes_rf.pkl')
joblib.dump(grid_dk.best_estimator_, 'diabetes_knn.pkl')
joblib.dump(grid_ds.best_estimator_, 'diabetes_svm.pkl')
joblib.dump(grid_dn.best_estimator_, 'diabetes_nb.pkl')
joblib.dump(scaler, 'diabetes_scaler.pkl')  # use whatever name the earlier dir() check confirmed

thresholds_d = {'rf': 0.539, 'knn': 0.330, 'svm': 0.328, 'nb': 0.462, 'combination_rule': 'majority_vote'}
with open('diabetes_thresholds.json', 'w') as f:
    json.dump(thresholds_d, f)

print("Diabetes saved.")

Diabetes saved.

In [171]:
joblib.dump(grid_kr.best_estimator_, 'ckd_rf.pkl')
joblib.dump(grid_kk.best_estimator_, 'ckd_knn.pkl')
joblib.dump(grid_ks.best_estimator_, 'ckd_svm.pkl')
joblib.dump(grid_kn.best_estimator_, 'ckd_nb.pkl')
joblib.dump(scaler_k, 'ckd_scaler.pkl')

thresholds_k = {'rf': 0.48, 'knn': 0.141, 'svm': 0.308, 'nb': 7.742932e-16, 'combination_rule': 'majority_vote'}
with open('ckd_thresholds.json', 'w') as f:
    json.dump(thresholds_k, f)

print("CKD saved.")

CKD saved.

In [172]:
for disease, X_test_var, y_test_var in [('heart', X_test_h, y_test_h), ('diabetes', X_test_d, y_test_d), ('ckd', X_test_k, y_test_k)]:
    models, scaler_loaded, thresholds_loaded = load_disease_pipeline(disease)
    sample_raw = X_test_var.iloc[[0]]
    sample_scaled = scaler_loaded.transform(sample_raw)
    result = predict_pipeline(sample_raw, sample_scaled, models, thresholds_loaded)
    print(f"{disease}: {result} | actual: {y_test_var.iloc[0]}")

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- ca
- chol
- cp
- exang
- fbs
- ...
Feature names seen at fit time, yet now missing:
- age_waist_interaction
- bp.1d
- bp.1s
- fasting
- glucose_fasting_interaction
- ...

In [173]:
import joblib

test_scaler = joblib.load('heart_scaler.pkl')
print("Number of features this scaler expects:", test_scaler.n_features_in_)

print("Heart disease has this many features:", X_test_h.shape[1])
print("Diabetes has this many features:", X_test_d.shape[1])

# Try transforming with EACH test set to see which one doesn't error
try:
    test_scaler.transform(X_test_h)
    print("heart_scaler.pkl WORKS with heart disease data")
except Exception as e:
    print("heart_scaler.pkl FAILS with heart disease data:", str(e)[:150])

try:
    test_scaler.transform(X_test_d)
    print("heart_scaler.pkl WORKS with diabetes data")
except Exception as e:
    print("heart_scaler.pkl FAILS with diabetes data:", str(e)[:150])

Number of features this scaler expects: 13
Heart disease has this many features: 13
Diabetes has this many features: 13
heart_scaler.pkl FAILS with heart disease data: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- ca
- chol
- cp
- exang
- fbs
- ...
Feature names
heart_scaler.pkl WORKS with diabetes data

In [174]:
import joblib

joblib.dump(scaler_h, 'heart_scaler.pkl')
print("Re-saved heart_scaler.pkl")

# Immediately verify it worked
test_scaler = joblib.load('heart_scaler.pkl')
test_scaler.transform(X_test_h)
print("✅ Confirmed: heart_scaler.pkl now correctly matches heart disease data")

Re-saved heart_scaler.pkl
✅ Confirmed: heart_scaler.pkl now correctly matches heart disease data

In [175]:
models_h, scaler_h_loaded, thresholds_h_loaded = load_disease_pipeline('heart')

sample_raw_h = X_test_h.iloc[[0]]
sample_scaled_h = scaler_h_loaded.transform(sample_raw_h)

result_h = predict_pipeline(sample_raw_h, sample_scaled_h, models_h, thresholds_h_loaded)
print(result_h)
print("Actual label:", y_test_h.iloc[0])

{'prediction': 1, 'confidence': np.float64(0.7877195678851711), 'stage_used': 'Stage 1 (Random Forest)'}
Actual label: 1

C:\Users\wilso\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2684: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(

In [176]:
# Check diabetes_scaler.pkl first
test_scaler_d = joblib.load('diabetes_scaler.pkl')
print("diabetes_scaler.pkl expects:", test_scaler_d.n_features_in_, "features")

try:
    test_scaler_d.transform(X_test_d)
    print("✅ diabetes_scaler.pkl correctly matches diabetes data")
except Exception as e:
    print("❌ diabetes_scaler.pkl does NOT match diabetes data:", str(e)[:200])

diabetes_scaler.pkl expects: 13 features
✅ diabetes_scaler.pkl correctly matches diabetes data

In [177]:
models_d, scaler_d_loaded, thresholds_d_loaded = load_disease_pipeline('diabetes')

sample_raw_d = X_test_d.iloc[[0]]
sample_scaled_d = scaler_d_loaded.transform(sample_raw_d)

result_d = predict_pipeline(sample_raw_d, sample_scaled_d, models_d, thresholds_d_loaded)
print(result_d)
print("Actual label:", y_test_d.iloc[0])

{'prediction': 0, 'confidence': np.float64(0.10075768051907479), 'stage_used': 'Stage 2 (Ensemble - Majority Vote)', 'individual_votes': {'knn': 0, 'svm': 0, 'nb': 0}}
Actual label: 1

In [178]:
import pandas as pd

results_list = []
for i in range(20):  # check first 20 rows
    sample_raw = X_test_d.iloc[[i]]
    sample_scaled = scaler_d_loaded.transform(sample_raw)
    result = predict_pipeline(sample_raw, sample_scaled, models_d, thresholds_d_loaded)
    results_list.append({
        'row': i,
        'predicted': result['prediction'],
        'actual': y_test_d.iloc[i],
        'stage': result['stage_used']
    })

df_check = pd.DataFrame(results_list)
print(df_check)
print()
print("Matches:", (df_check['predicted'] == df_check['actual']).sum(), "out of", len(df_check))

    row  predicted  actual                               stage
0     0          0       1  Stage 2 (Ensemble - Majority Vote)
1     1          1       1             Stage 1 (Random Forest)
2     2          0       0  Stage 2 (Ensemble - Majority Vote)
3     3          0       0  Stage 2 (Ensemble - Majority Vote)
4     4          0       0  Stage 2 (Ensemble - Majority Vote)
5     5          0       0  Stage 2 (Ensemble - Majority Vote)
6     6          1       1             Stage 1 (Random Forest)
7     7          0       0  Stage 2 (Ensemble - Majority Vote)
8     8          0       0  Stage 2 (Ensemble - Majority Vote)
9     9          1       0  Stage 2 (Ensemble - Majority Vote)
10   10          1       1             Stage 1 (Random Forest)
11   11          1       1             Stage 1 (Random Forest)
12   12          0       0  Stage 2 (Ensemble - Majority Vote)
13   13          0       0  Stage 2 (Ensemble - Majority Vote)
14   14          0       0  Stage 2 (Ensemble - Majority Vote)
15   15          0       0  Stage 2 (Ensemble - Majority Vote)
16   16          1       1             Stage 1 (Random Forest)
17   17          1       0             Stage 1 (Random Forest)
18   18          0       0  Stage 2 (Ensemble - Majority Vote)
19   19          0       0  Stage 2 (Ensemble - Majority Vote)

Matches: 17 out of 20

In [179]:
models_k, scaler_k_loaded, thresholds_k_loaded = load_disease_pipeline('ckd')

results_list_k = []
for i in range(20):
    sample_raw = X_test_k.iloc[[i]]
    sample_scaled = scaler_k_loaded.transform(sample_raw)
    result = predict_pipeline(sample_raw, sample_scaled, models_k, thresholds_k_loaded)
    results_list_k.append({
        'row': i,
        'predicted': result['prediction'],
        'actual': y_test_k.iloc[i],
        'stage': result['stage_used']
    })

df_check_k = pd.DataFrame(results_list_k)
print(df_check_k)
print()
print("Matches:", (df_check_k['predicted'] == df_check_k['actual']).sum(), "out of", len(df_check_k))

    row  predicted  actual                               stage
0     0          1       1             Stage 1 (Random Forest)
1     1          1       1             Stage 1 (Random Forest)
2     2          1       1             Stage 1 (Random Forest)
3     3          1       1             Stage 1 (Random Forest)
4     4          1       1             Stage 1 (Random Forest)
5     5          1       1             Stage 1 (Random Forest)
6     6          0       0  Stage 2 (Ensemble - Majority Vote)
7     7          1       1             Stage 1 (Random Forest)
8     8          0       0  Stage 2 (Ensemble - Majority Vote)
9     9          1       1             Stage 1 (Random Forest)
10   10          1       1             Stage 1 (Random Forest)
11   11          1       1             Stage 1 (Random Forest)
12   12          0       0  Stage 2 (Ensemble - Majority Vote)
13   13          1       1             Stage 1 (Random Forest)
14   14          0       0  Stage 2 (Ensemble - Majority Vote)
15   15          0       0  Stage 2 (Ensemble - Majority Vote)
16   16          1       1             Stage 1 (Random Forest)
17   17          0       0  Stage 2 (Ensemble - Majority Vote)
18   18          0       0  Stage 2 (Ensemble - Majority Vote)
19   19          1       1             Stage 1 (Random Forest)

Matches: 20 out of 20

In [180]:
heart_normal_ranges = {
    'trestbps': (90, 130),      # resting blood pressure (mm Hg)
    'chol': (125, 200),         # serum cholesterol (mg/dl)
    'thalach': (100, 170),      # max heart rate achieved — context-dependent on age, rough general band
    'oldpeak': (0, 1),          # ST depression — above 1 suggests more cardiac stress
    'ca': (0, 0),               # number of major vessels blocked — 0 is ideal, >0 flags concern
    'age': (0, 55),             # flags "older age" as a risk contributor beyond this
}

heart_clinical_advice = {
    'trestbps': "your resting blood pressure is elevated — consider reducing sodium intake and increasing physical activity",
    'chol': "your cholesterol is above the healthy range — consider dietary changes and discussing statin therapy with your doctor",
    'thalach': "your maximum heart rate response is lower than typical — this may reflect reduced cardiovascular fitness, worth discussing with your doctor",
    'oldpeak': "your ST depression value suggests notable cardiac stress during exercise — this warrants a cardiology follow-up",
    'ca': "you have blocked major vessels detected via imaging — this is a significant finding requiring cardiology follow-up",
    'age': "age is a non-modifiable risk factor, but managing other risk factors becomes more important as you get older",
}

def generate_heart_explanation(patient_data, rf_model, feature_names):
    importances = pd.Series(rf_model.feature_importances_, index=feature_names).sort_values(ascending=False)

    reasons = []
    for feature in importances.index:
        if feature not in heart_normal_ranges:
            continue
        value = patient_data[feature].values[0]
        low, high = heart_normal_ranges[feature]
        if value < low or value > high:
            advice = heart_clinical_advice.get(feature, "consider discussing this with your doctor")
            reasons.append(f"{feature} ({value:.1f}) is outside the typical range — {advice}")
        if len(reasons) >= 3:
            break

    return reasons if reasons else ["No individually abnormal high-impact factors found, but overall pattern still suggests risk — consult a doctor."]

In [181]:
ckd_normal_ranges = {
    'bgr': (70, 140),      # blood glucose random (mg/dl)
    'bu': (7, 20),         # blood urea (mg/dl)
    'sc': (0.6, 1.3),      # serum creatinine (mg/dl) — key kidney marker
    'sod': (135, 145),     # sodium (mEq/L)
    'pot': (3.5, 5.0),     # potassium (mEq/L)
    'hemo': (12, 17),      # hemoglobin (g/dl)
    'pcv': (36, 50),       # packed cell volume (%)
    'sg': (1.015, 1.025),  # urine specific gravity
    'al': (0, 0),          # albumin in urine — 0 is normal, any presence flags kidney concern
}

ckd_clinical_advice = {
    'bgr': "your blood glucose is outside the normal range — managing blood sugar can help protect kidney function",
    'bu': "your blood urea level is abnormal — this reflects how well your kidneys are filtering waste, worth discussing with a nephrologist",
    'sc': "your serum creatinine is outside the normal range — this is a key marker of kidney filtration function and needs medical follow-up",
    'sod': "your sodium level is abnormal — this can affect fluid balance and kidney function, worth monitoring with your doctor",
    'pot': "your potassium level is outside the normal range — this is important to monitor closely, especially with kidney concerns",
    'hemo': "your hemoglobin is low — reduced kidney function can affect red blood cell production, discuss with your doctor",
    'pcv': "your packed cell volume is abnormal — this may relate to anemia associated with kidney function decline",
    'sg': "your urine specific gravity is abnormal — this reflects how well your kidneys are concentrating urine",
    'al': "protein (albumin) detected in your urine — this is an important early indicator of kidney damage and should be followed up",
}

def generate_ckd_explanation(patient_data, rf_model, feature_names):
    importances = pd.Series(rf_model.feature_importances_, index=feature_names).sort_values(ascending=False)

    reasons = []
    for feature in importances.index:
        if feature not in ckd_normal_ranges:
            continue
        value = patient_data[feature].values[0]
        low, high = ckd_normal_ranges[feature]
        if value < low or value > high:
            advice = ckd_clinical_advice.get(feature, "consider discussing this with your doctor")
            reasons.append(f"{feature} ({value:.2f}) is outside the typical range — {advice}")
        if len(reasons) >= 3:
            break

    return reasons if reasons else ["No individually abnormal high-impact factors found, but overall pattern still suggests risk — consult a doctor."]

In [182]:
diabetes_normal_ranges = {
    'stab.glu': (70, 140),                    # stabilized glucose (mg/dl)
    'chol': (125, 200),                       # total cholesterol (mg/dl)
    'ratio': (0, 5),                          # cholesterol/HDL ratio — above 5 is a risk indicator
    'hdl': (40, 100),                         # HDL cholesterol (mg/dl) — below 40 is a risk factor
    'bp.1s': (90, 130),                       # systolic blood pressure
    'bp.1d': (60, 85),                        # diastolic blood pressure
    'waist': (0, 40),                         # waist circumference (inches) — general risk threshold
    'whr': (0, 0.9),                          # waist-to-hip ratio — above 0.9 (men) / 0.85 (women) is a risk marker
    'age_waist_interaction': (0, 2000),       # engineered feature — flag high compounded risk
    'glucose_fasting_interaction': (0, 140),  # engineered feature — flags high fasting glucose specifically
}

diabetes_clinical_advice = {
    'stab.glu': "your glucose level is elevated — reducing sugar and refined carbohydrate intake can help lower this",
    'chol': "your total cholesterol is above the healthy range — consider dietary changes and discussing this with your doctor",
    'ratio': "your cholesterol-to-HDL ratio is elevated, suggesting higher cardiovascular/metabolic risk — regular exercise can help improve this",
    'hdl': "your HDL ('good') cholesterol is lower than ideal — regular aerobic exercise can help raise it",
    'bp.1s': "your systolic blood pressure is elevated — reducing sodium intake and increasing physical activity may help",
    'bp.1d': "your diastolic blood pressure is elevated — lifestyle changes like reducing salt and stress can help",
    'waist': "your waist circumference suggests higher abdominal fat, a known diabetes risk factor — regular exercise and dietary changes can help",
    'whr': "your waist-to-hip ratio indicates higher abdominal fat distribution, which is strongly linked to insulin resistance",
    'age_waist_interaction': "the combination of your age and waist measurement suggests compounded metabolic risk — worth discussing with your doctor",
    'glucose_fasting_interaction': "your fasting glucose reading is elevated — this is a key diabetes screening indicator and should be discussed with your doctor",
}

def generate_diabetes_explanation(patient_data, rf_model, feature_names):
    importances = pd.Series(rf_model.feature_importances_, index=feature_names).sort_values(ascending=False)

    reasons = []
    for feature in importances.index:
        if feature not in diabetes_normal_ranges:
            continue
        value = patient_data[feature].values[0]
        low, high = diabetes_normal_ranges[feature]
        if value < low or value > high:
            advice = diabetes_clinical_advice.get(feature, "consider discussing this with your doctor")
            reasons.append(f"{feature} ({value:.2f}) is outside the typical range — {advice}")
        if len(reasons) >= 3:
            break

    return reasons if reasons else ["No individually abnormal high-impact factors found, but overall pattern still suggests risk — consult a doctor."]

In [183]:
sample_d = X_test_d.iloc[[0]]
explanation_d = generate_diabetes_explanation(sample_d, models_d['rf'], X_test_d.columns.tolist())
print("Diabetes explanation:", explanation_d)

Diabetes explanation: ['bp.1s (144.00) is outside the typical range — your systolic blood pressure is elevated — reducing sodium intake and increasing physical activity may help', 'bp.1d (94.00) is outside the typical range — your diastolic blood pressure is elevated — lifestyle changes like reducing salt and stress can help']

In [184]:
# Heart disease example
sample_h = X_test_h.iloc[[0]]
explanation_h = generate_heart_explanation(sample_h, models_h['rf'], X_test_h.columns.tolist())
print("Heart disease explanation:", explanation_h)

# CKD example
sample_k = X_test_k.iloc[[0]]
explanation_k = generate_ckd_explanation(sample_k, models_k['rf'], X_test_k.columns.tolist())
print("CKD explanation:", explanation_k)

Heart disease explanation: ['ca (1.0) is outside the typical range — you have blocked major vessels detected via imaging — this is a significant finding requiring cardiology follow-up', 'chol (206.0) is outside the typical range — your cholesterol is above the healthy range — consider dietary changes and discussing statin therapy with your doctor']
CKD explanation: ['hemo (10.65) is outside the typical range — your hemoglobin is low — reduced kidney function can affect red blood cell production, discuss with your doctor', 'pcv (31.55) is outside the typical range — your packed cell volume is abnormal — this may relate to anemia associated with kidney function decline', 'al (3.00) is outside the typical range — protein (albumin) detected in your urine — this is an important early indicator of kidney damage and should be followed up']